"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .apierror import APIError
    from .auth_login_body import AuthLoginBody, AuthLoginBodyTypedDict
    from .authstartbody import AuthStartBody, AuthStartBodyTypedDict
    from .authstartresponse import AuthStartResponse, AuthStartResponseTypedDict
    from .authstatus import AuthStatus, AuthStatusTypedDict, AuthType
    from .callconnectiontoolop import (
        CallConnectionToolRequest,
        CallConnectionToolRequestTypedDict,
        CallConnectionToolSecurity,
        CallConnectionToolSecurityTypedDict,
    )
    from .cancelconnectionrequestop import (
        CancelConnectionRequestRequest,
        CancelConnectionRequestRequestTypedDict,
        CancelConnectionRequestSecurity,
        CancelConnectionRequestSecurityTypedDict,
    )
    from .cancelrequestbody import CancelRequestBody, CancelRequestBodyTypedDict
    from .capability import Capability, CapabilityTypedDict
    from .completions_body import CompletionsBody, CompletionsBodyTypedDict
    from .connection import Connection, ConnectionStatus, ConnectionTypedDict, Transport
    from .connectioninitializebody import (
        ConnectionInitializeBody,
        ConnectionInitializeBodyTypedDict,
    )
    from .connectioninitializeresponse import (
        ConnectionInitializeResponse,
        ConnectionInitializeResponseTypedDict,
    )
    from .connections_body import (
        ConnectionsBody,
        ConnectionsBodyTransport,
        ConnectionsBodyTypedDict,
        Options,
        OptionsTypedDict,
    )
    from .context import Context, ContextTypedDict
    from .createconnectionop import (
        CreateConnectionSecurity,
        CreateConnectionSecurityTypedDict,
    )
    from .deleteconnectionop import (
        DeleteConnectionRequest,
        DeleteConnectionRequestTypedDict,
        DeleteConnectionSecurity,
        DeleteConnectionSecurityTypedDict,
    )
    from .error import Error, ErrorData
    from .getconnectionauthstatusop import (
        GetConnectionAuthStatusRequest,
        GetConnectionAuthStatusRequestTypedDict,
        GetConnectionAuthStatusSecurity,
        GetConnectionAuthStatusSecurityTypedDict,
    )
    from .getconnectionbyidop import (
        GetConnectionByIDRequest,
        GetConnectionByIDRequestTypedDict,
        GetConnectionByIDSecurity,
        GetConnectionByIDSecurityTypedDict,
    )
    from .getconnectioncapabilitiesop import (
        GetConnectionCapabilitiesRequest,
        GetConnectionCapabilitiesRequestTypedDict,
        GetConnectionCapabilitiesSecurity,
        GetConnectionCapabilitiesSecurityTypedDict,
    )
    from .getconnectionpromptop import (
        GetConnectionPromptRequest,
        GetConnectionPromptRequestTypedDict,
        GetConnectionPromptSecurity,
        GetConnectionPromptSecurityTypedDict,
    )
    from .getcontextbyidop import (
        GetContextByIDRequest,
        GetContextByIDRequestTypedDict,
        GetContextByIDSecurity,
        GetContextByIDSecurityTypedDict,
    )
    from .getcurrentuserop import (
        GetCurrentUserSecurity,
        GetCurrentUserSecurityTypedDict,
    )
    from .getmcpserverbyidop import (
        GetMcpServerByIDRequest,
        GetMcpServerByIDRequestTypedDict,
        GetMcpServerByIDSecurity,
        GetMcpServerByIDSecurityTypedDict,
    )
    from .getpromptbyidop import (
        GetPromptByIDRequest,
        GetPromptByIDRequestTypedDict,
        GetPromptByIDSecurity,
        GetPromptByIDSecurityTypedDict,
    )
    from .getrequestdetailsop import (
        GetRequestDetailsRequest,
        GetRequestDetailsRequestTypedDict,
        GetRequestDetailsSecurity,
        GetRequestDetailsSecurityTypedDict,
    )
    from .getsystemhealthop import (
        GetSystemHealthRequest,
        GetSystemHealthRequestTypedDict,
    )
    from .gettoolbyidop import (
        GetToolByIDRequest,
        GetToolByIDRequestTypedDict,
        GetToolByIDSecurity,
        GetToolByIDSecurityTypedDict,
    )
    from .initializeconnectionop import (
        InitializeConnectionRequest,
        InitializeConnectionRequestTypedDict,
        InitializeConnectionSecurity,
        InitializeConnectionSecurityTypedDict,
    )
    from .inline_response_200 import InlineResponse200, InlineResponse200TypedDict
    from .inline_response_200_1 import InlineResponse2001, InlineResponse2001TypedDict
    from .inline_response_200_2 import InlineResponse2002, InlineResponse2002TypedDict
    from .inline_response_200_3 import (
        InlineResponse2003,
        InlineResponse2003Role,
        InlineResponse2003TypedDict,
    )
    from .inline_response_200_4 import InlineResponse2004, InlineResponse2004TypedDict
    from .inline_response_200_5 import InlineResponse2005, InlineResponse2005TypedDict
    from .inline_response_200_6 import InlineResponse2006, InlineResponse2006TypedDict
    from .inline_response_200_7 import (
        InlineResponse2007,
        InlineResponse2007TypedDict,
        Metadata,
        MetadataTypedDict,
    )
    from .inline_response_200_8 import (
        InlineResponse2008,
        InlineResponse2008Metadata,
        InlineResponse2008MetadataTypedDict,
        InlineResponse2008TypedDict,
        Results,
        ResultsTypedDict,
    )
    from .inline_response_202 import InlineResponse202, InlineResponse202TypedDict
    from .listcapabilitiesop import (
        ListCapabilitiesSecurity,
        ListCapabilitiesSecurityTypedDict,
    )
    from .listconnectionpromptsop import (
        ListConnectionPromptsRequest,
        ListConnectionPromptsRequestTypedDict,
        ListConnectionPromptsSecurity,
        ListConnectionPromptsSecurityTypedDict,
    )
    from .listconnectionresourcesop import (
        ListConnectionResourcesRequest,
        ListConnectionResourcesRequestTypedDict,
        ListConnectionResourcesSecurity,
        ListConnectionResourcesSecurityTypedDict,
    )
    from .listconnectionsop import (
        ListConnectionsSecurity,
        ListConnectionsSecurityTypedDict,
    )
    from .listconnectiontoolsop import (
        ListConnectionToolsRequest,
        ListConnectionToolsRequestTypedDict,
        ListConnectionToolsSecurity,
        ListConnectionToolsSecurityTypedDict,
    )
    from .listcontextsop import (
        ListContextsRequest,
        ListContextsRequestTypedDict,
        ListContextsSecurity,
        ListContextsSecurityTypedDict,
    )
    from .listmcpserversop import (
        ListMcpServersRequest,
        ListMcpServersRequestTypedDict,
        ListMcpServersSecurity,
        ListMcpServersSecurityTypedDict,
        QueryParamStatus,
    )
    from .listmodelsincontextop import (
        ListModelsInContextRequest,
        ListModelsInContextRequestTypedDict,
        ListModelsInContextSecurity,
        ListModelsInContextSecurityTypedDict,
    )
    from .listpromptsop import ListPromptsSecurity, ListPromptsSecurityTypedDict
    from .listresourcesop import (
        ListResourcesRequest,
        ListResourcesRequestTypedDict,
        ListResourcesSecurity,
        ListResourcesSecurityTypedDict,
    )
    from .listresourcetemplatesop import (
        ListResourceTemplatesSecurity,
        ListResourceTemplatesSecurityTypedDict,
    )
    from .listtoolsop import ListToolsSecurity, ListToolsSecurityTypedDict
    from .logging_level_body import Level, LoggingLevelBody, LoggingLevelBodyTypedDict
    from .mcpserver import McpServer, McpServerTypedDict, Status
    from .model import Model, ModelTypedDict
    from .pingconnectionop import (
        PingConnectionRequest,
        PingConnectionRequestTypedDict,
        PingConnectionSecurity,
        PingConnectionSecurityTypedDict,
    )
    from .postcompletionop import (
        PostCompletionSecurity,
        PostCompletionSecurityTypedDict,
    )
    from .postlogoutop import PostLogoutSecurity, PostLogoutSecurityTypedDict
    from .postnotifyownerop import (
        PostNotifyOwnerSecurity,
        PostNotifyOwnerSecurityTypedDict,
    )
    from .postqueryop import PostQuerySecurity, PostQuerySecurityTypedDict
    from .prompt import Prompt, PromptTypedDict
    from .promptgetbody import PromptGetBody, PromptGetBodyTypedDict
    from .queries_body import QueriesBody, QueriesBodyTypedDict
    from .readconnectionresourceop import (
        ReadConnectionResourceRequest,
        ReadConnectionResourceRequestTypedDict,
        ReadConnectionResourceSecurity,
        ReadConnectionResourceSecurityTypedDict,
    )
    from .readresourceop import (
        ReadResourceRequest,
        ReadResourceRequestTypedDict,
        ReadResourceSecurity,
        ReadResourceSecurityTypedDict,
    )
    from .registermcpserverop import (
        RegisterMcpServerSecurity,
        RegisterMcpServerSecurityTypedDict,
    )
    from .requestdetails import (
        RequestDetails,
        RequestDetailsStatus,
        RequestDetailsTypedDict,
    )
    from .requestdetails_events import (
        RequestDetailsEvents,
        RequestDetailsEventsTypedDict,
    )
    from .resource import Resource, ResourceTypedDict
    from .resourcereadbody import ResourceReadBody, ResourceReadBodyTypedDict
    from .resourcetemplate import ResourceTemplate, ResourceTemplateTypedDict
    from .security import Security, SecurityTypedDict
    from .servers_body import ServersBody, ServersBodyTypedDict
    from .setlogginglevelop import (
        SetLoggingLevelSecurity,
        SetLoggingLevelSecurityTypedDict,
    )
    from .startconnectionauthop import (
        StartConnectionAuthRequest,
        StartConnectionAuthRequestTypedDict,
        StartConnectionAuthSecurity,
        StartConnectionAuthSecurityTypedDict,
    )
    from .streameventsop import StreamEventsSecurity, StreamEventsSecurityTypedDict
    from .subscriberesourceop import (
        SubscribeResourceRequest,
        SubscribeResourceRequestTypedDict,
        SubscribeResourceSecurity,
        SubscribeResourceSecurityTypedDict,
    )
    from .system_notifyowner_body import (
        SystemNotifyOwnerBody,
        SystemNotifyOwnerBodyTypedDict,
    )
    from .tool import Tool, ToolTypedDict
    from .toolcallbody import ToolCallBody, ToolCallBodyTypedDict
    from .toolcallresult import ToolCallResult, ToolCallResultTypedDict
    from .transportoptionsstdio import (
        TransportOptionsStdio,
        TransportOptionsStdioTypedDict,
    )
    from .transportoptionsstreamablehttp import (
        TransportOptionsStreamableHTTP,
        TransportOptionsStreamableHTTPTypedDict,
    )
    from .unsubscriberesourceop import (
        UnsubscribeResourceRequest,
        UnsubscribeResourceRequestTypedDict,
        UnsubscribeResourceSecurity,
        UnsubscribeResourceSecurityTypedDict,
    )
    from .user import Role, User, UserTypedDict

__all__ = [
    "APIError",
    "AuthLoginBody",
    "AuthLoginBodyTypedDict",
    "AuthStartBody",
    "AuthStartBodyTypedDict",
    "AuthStartResponse",
    "AuthStartResponseTypedDict",
    "AuthStatus",
    "AuthStatusTypedDict",
    "AuthType",
    "CallConnectionToolRequest",
    "CallConnectionToolRequestTypedDict",
    "CallConnectionToolSecurity",
    "CallConnectionToolSecurityTypedDict",
    "CancelConnectionRequestRequest",
    "CancelConnectionRequestRequestTypedDict",
    "CancelConnectionRequestSecurity",
    "CancelConnectionRequestSecurityTypedDict",
    "CancelRequestBody",
    "CancelRequestBodyTypedDict",
    "Capability",
    "CapabilityTypedDict",
    "CompletionsBody",
    "CompletionsBodyTypedDict",
    "Connection",
    "ConnectionInitializeBody",
    "ConnectionInitializeBodyTypedDict",
    "ConnectionInitializeResponse",
    "ConnectionInitializeResponseTypedDict",
    "ConnectionStatus",
    "ConnectionTypedDict",
    "ConnectionsBody",
    "ConnectionsBodyTransport",
    "ConnectionsBodyTypedDict",
    "Context",
    "ContextTypedDict",
    "CreateConnectionSecurity",
    "CreateConnectionSecurityTypedDict",
    "DeleteConnectionRequest",
    "DeleteConnectionRequestTypedDict",
    "DeleteConnectionSecurity",
    "DeleteConnectionSecurityTypedDict",
    "Error",
    "ErrorData",
    "GetConnectionAuthStatusRequest",
    "GetConnectionAuthStatusRequestTypedDict",
    "GetConnectionAuthStatusSecurity",
    "GetConnectionAuthStatusSecurityTypedDict",
    "GetConnectionByIDRequest",
    "GetConnectionByIDRequestTypedDict",
    "GetConnectionByIDSecurity",
    "GetConnectionByIDSecurityTypedDict",
    "GetConnectionCapabilitiesRequest",
    "GetConnectionCapabilitiesRequestTypedDict",
    "GetConnectionCapabilitiesSecurity",
    "GetConnectionCapabilitiesSecurityTypedDict",
    "GetConnectionPromptRequest",
    "GetConnectionPromptRequestTypedDict",
    "GetConnectionPromptSecurity",
    "GetConnectionPromptSecurityTypedDict",
    "GetContextByIDRequest",
    "GetContextByIDRequestTypedDict",
    "GetContextByIDSecurity",
    "GetContextByIDSecurityTypedDict",
    "GetCurrentUserSecurity",
    "GetCurrentUserSecurityTypedDict",
    "GetMcpServerByIDRequest",
    "GetMcpServerByIDRequestTypedDict",
    "GetMcpServerByIDSecurity",
    "GetMcpServerByIDSecurityTypedDict",
    "GetPromptByIDRequest",
    "GetPromptByIDRequestTypedDict",
    "GetPromptByIDSecurity",
    "GetPromptByIDSecurityTypedDict",
    "GetRequestDetailsRequest",
    "GetRequestDetailsRequestTypedDict",
    "GetRequestDetailsSecurity",
    "GetRequestDetailsSecurityTypedDict",
    "GetSystemHealthRequest",
    "GetSystemHealthRequestTypedDict",
    "GetToolByIDRequest",
    "GetToolByIDRequestTypedDict",
    "GetToolByIDSecurity",
    "GetToolByIDSecurityTypedDict",
    "InitializeConnectionRequest",
    "InitializeConnectionRequestTypedDict",
    "InitializeConnectionSecurity",
    "InitializeConnectionSecurityTypedDict",
    "InlineResponse200",
    "InlineResponse2001",
    "InlineResponse2001TypedDict",
    "InlineResponse2002",
    "InlineResponse2002TypedDict",
    "InlineResponse2003",
    "InlineResponse2003Role",
    "InlineResponse2003TypedDict",
    "InlineResponse2004",
    "InlineResponse2004TypedDict",
    "InlineResponse2005",
    "InlineResponse2005TypedDict",
    "InlineResponse2006",
    "InlineResponse2006TypedDict",
    "InlineResponse2007",
    "InlineResponse2007TypedDict",
    "InlineResponse2008",
    "InlineResponse2008Metadata",
    "InlineResponse2008MetadataTypedDict",
    "InlineResponse2008TypedDict",
    "InlineResponse200TypedDict",
    "InlineResponse202",
    "InlineResponse202TypedDict",
    "Level",
    "ListCapabilitiesSecurity",
    "ListCapabilitiesSecurityTypedDict",
    "ListConnectionPromptsRequest",
    "ListConnectionPromptsRequestTypedDict",
    "ListConnectionPromptsSecurity",
    "ListConnectionPromptsSecurityTypedDict",
    "ListConnectionResourcesRequest",
    "ListConnectionResourcesRequestTypedDict",
    "ListConnectionResourcesSecurity",
    "ListConnectionResourcesSecurityTypedDict",
    "ListConnectionToolsRequest",
    "ListConnectionToolsRequestTypedDict",
    "ListConnectionToolsSecurity",
    "ListConnectionToolsSecurityTypedDict",
    "ListConnectionsSecurity",
    "ListConnectionsSecurityTypedDict",
    "ListContextsRequest",
    "ListContextsRequestTypedDict",
    "ListContextsSecurity",
    "ListContextsSecurityTypedDict",
    "ListMcpServersRequest",
    "ListMcpServersRequestTypedDict",
    "ListMcpServersSecurity",
    "ListMcpServersSecurityTypedDict",
    "ListModelsInContextRequest",
    "ListModelsInContextRequestTypedDict",
    "ListModelsInContextSecurity",
    "ListModelsInContextSecurityTypedDict",
    "ListPromptsSecurity",
    "ListPromptsSecurityTypedDict",
    "ListResourceTemplatesSecurity",
    "ListResourceTemplatesSecurityTypedDict",
    "ListResourcesRequest",
    "ListResourcesRequestTypedDict",
    "ListResourcesSecurity",
    "ListResourcesSecurityTypedDict",
    "ListToolsSecurity",
    "ListToolsSecurityTypedDict",
    "LoggingLevelBody",
    "LoggingLevelBodyTypedDict",
    "McpServer",
    "McpServerTypedDict",
    "Metadata",
    "MetadataTypedDict",
    "Model",
    "ModelTypedDict",
    "Options",
    "OptionsTypedDict",
    "PingConnectionRequest",
    "PingConnectionRequestTypedDict",
    "PingConnectionSecurity",
    "PingConnectionSecurityTypedDict",
    "PostCompletionSecurity",
    "PostCompletionSecurityTypedDict",
    "PostLogoutSecurity",
    "PostLogoutSecurityTypedDict",
    "PostNotifyOwnerSecurity",
    "PostNotifyOwnerSecurityTypedDict",
    "PostQuerySecurity",
    "PostQuerySecurityTypedDict",
    "Prompt",
    "PromptGetBody",
    "PromptGetBodyTypedDict",
    "PromptTypedDict",
    "QueriesBody",
    "QueriesBodyTypedDict",
    "QueryParamStatus",
    "ReadConnectionResourceRequest",
    "ReadConnectionResourceRequestTypedDict",
    "ReadConnectionResourceSecurity",
    "ReadConnectionResourceSecurityTypedDict",
    "ReadResourceRequest",
    "ReadResourceRequestTypedDict",
    "ReadResourceSecurity",
    "ReadResourceSecurityTypedDict",
    "RegisterMcpServerSecurity",
    "RegisterMcpServerSecurityTypedDict",
    "RequestDetails",
    "RequestDetailsEvents",
    "RequestDetailsEventsTypedDict",
    "RequestDetailsStatus",
    "RequestDetailsTypedDict",
    "Resource",
    "ResourceReadBody",
    "ResourceReadBodyTypedDict",
    "ResourceTemplate",
    "ResourceTemplateTypedDict",
    "ResourceTypedDict",
    "Results",
    "ResultsTypedDict",
    "Role",
    "Security",
    "SecurityTypedDict",
    "ServersBody",
    "ServersBodyTypedDict",
    "SetLoggingLevelSecurity",
    "SetLoggingLevelSecurityTypedDict",
    "StartConnectionAuthRequest",
    "StartConnectionAuthRequestTypedDict",
    "StartConnectionAuthSecurity",
    "StartConnectionAuthSecurityTypedDict",
    "Status",
    "StreamEventsSecurity",
    "StreamEventsSecurityTypedDict",
    "SubscribeResourceRequest",
    "SubscribeResourceRequestTypedDict",
    "SubscribeResourceSecurity",
    "SubscribeResourceSecurityTypedDict",
    "SystemNotifyOwnerBody",
    "SystemNotifyOwnerBodyTypedDict",
    "Tool",
    "ToolCallBody",
    "ToolCallBodyTypedDict",
    "ToolCallResult",
    "ToolCallResultTypedDict",
    "ToolTypedDict",
    "Transport",
    "TransportOptionsStdio",
    "TransportOptionsStdioTypedDict",
    "TransportOptionsStreamableHTTP",
    "TransportOptionsStreamableHTTPTypedDict",
    "UnsubscribeResourceRequest",
    "UnsubscribeResourceRequestTypedDict",
    "UnsubscribeResourceSecurity",
    "UnsubscribeResourceSecurityTypedDict",
    "User",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "AuthLoginBody": ".auth_login_body",
    "AuthLoginBodyTypedDict": ".auth_login_body",
    "AuthStartBody": ".authstartbody",
    "AuthStartBodyTypedDict": ".authstartbody",
    "AuthStartResponse": ".authstartresponse",
    "AuthStartResponseTypedDict": ".authstartresponse",
    "AuthStatus": ".authstatus",
    "AuthStatusTypedDict": ".authstatus",
    "AuthType": ".authstatus",
    "CallConnectionToolRequest": ".callconnectiontoolop",
    "CallConnectionToolRequestTypedDict": ".callconnectiontoolop",
    "CallConnectionToolSecurity": ".callconnectiontoolop",
    "CallConnectionToolSecurityTypedDict": ".callconnectiontoolop",
    "CancelConnectionRequestRequest": ".cancelconnectionrequestop",
    "CancelConnectionRequestRequestTypedDict": ".cancelconnectionrequestop",
    "CancelConnectionRequestSecurity": ".cancelconnectionrequestop",
    "CancelConnectionRequestSecurityTypedDict": ".cancelconnectionrequestop",
    "CancelRequestBody": ".cancelrequestbody",
    "CancelRequestBodyTypedDict": ".cancelrequestbody",
    "Capability": ".capability",
    "CapabilityTypedDict": ".capability",
    "CompletionsBody": ".completions_body",
    "CompletionsBodyTypedDict": ".completions_body",
    "Connection": ".connection",
    "ConnectionStatus": ".connection",
    "ConnectionTypedDict": ".connection",
    "Transport": ".connection",
    "ConnectionInitializeBody": ".connectioninitializebody",
    "ConnectionInitializeBodyTypedDict": ".connectioninitializebody",
    "ConnectionInitializeResponse": ".connectioninitializeresponse",
    "ConnectionInitializeResponseTypedDict": ".connectioninitializeresponse",
    "ConnectionsBody": ".connections_body",
    "ConnectionsBodyTransport": ".connections_body",
    "ConnectionsBodyTypedDict": ".connections_body",
    "Options": ".connections_body",
    "OptionsTypedDict": ".connections_body",
    "Context": ".context",
    "ContextTypedDict": ".context",
    "CreateConnectionSecurity": ".createconnectionop",
    "CreateConnectionSecurityTypedDict": ".createconnectionop",
    "DeleteConnectionRequest": ".deleteconnectionop",
    "DeleteConnectionRequestTypedDict": ".deleteconnectionop",
    "DeleteConnectionSecurity": ".deleteconnectionop",
    "DeleteConnectionSecurityTypedDict": ".deleteconnectionop",
    "Error": ".error",
    "ErrorData": ".error",
    "GetConnectionAuthStatusRequest": ".getconnectionauthstatusop",
    "GetConnectionAuthStatusRequestTypedDict": ".getconnectionauthstatusop",
    "GetConnectionAuthStatusSecurity": ".getconnectionauthstatusop",
    "GetConnectionAuthStatusSecurityTypedDict": ".getconnectionauthstatusop",
    "GetConnectionByIDRequest": ".getconnectionbyidop",
    "GetConnectionByIDRequestTypedDict": ".getconnectionbyidop",
    "GetConnectionByIDSecurity": ".getconnectionbyidop",
    "GetConnectionByIDSecurityTypedDict": ".getconnectionbyidop",
    "GetConnectionCapabilitiesRequest": ".getconnectioncapabilitiesop",
    "GetConnectionCapabilitiesRequestTypedDict": ".getconnectioncapabilitiesop",
    "GetConnectionCapabilitiesSecurity": ".getconnectioncapabilitiesop",
    "GetConnectionCapabilitiesSecurityTypedDict": ".getconnectioncapabilitiesop",
    "GetConnectionPromptRequest": ".getconnectionpromptop",
    "GetConnectionPromptRequestTypedDict": ".getconnectionpromptop",
    "GetConnectionPromptSecurity": ".getconnectionpromptop",
    "GetConnectionPromptSecurityTypedDict": ".getconnectionpromptop",
    "GetContextByIDRequest": ".getcontextbyidop",
    "GetContextByIDRequestTypedDict": ".getcontextbyidop",
    "GetContextByIDSecurity": ".getcontextbyidop",
    "GetContextByIDSecurityTypedDict": ".getcontextbyidop",
    "GetCurrentUserSecurity": ".getcurrentuserop",
    "GetCurrentUserSecurityTypedDict": ".getcurrentuserop",
    "GetMcpServerByIDRequest": ".getmcpserverbyidop",
    "GetMcpServerByIDRequestTypedDict": ".getmcpserverbyidop",
    "GetMcpServerByIDSecurity": ".getmcpserverbyidop",
    "GetMcpServerByIDSecurityTypedDict": ".getmcpserverbyidop",
    "GetPromptByIDRequest": ".getpromptbyidop",
    "GetPromptByIDRequestTypedDict": ".getpromptbyidop",
    "GetPromptByIDSecurity": ".getpromptbyidop",
    "GetPromptByIDSecurityTypedDict": ".getpromptbyidop",
    "GetRequestDetailsRequest": ".getrequestdetailsop",
    "GetRequestDetailsRequestTypedDict": ".getrequestdetailsop",
    "GetRequestDetailsSecurity": ".getrequestdetailsop",
    "GetRequestDetailsSecurityTypedDict": ".getrequestdetailsop",
    "GetSystemHealthRequest": ".getsystemhealthop",
    "GetSystemHealthRequestTypedDict": ".getsystemhealthop",
    "GetToolByIDRequest": ".gettoolbyidop",
    "GetToolByIDRequestTypedDict": ".gettoolbyidop",
    "GetToolByIDSecurity": ".gettoolbyidop",
    "GetToolByIDSecurityTypedDict": ".gettoolbyidop",
    "InitializeConnectionRequest": ".initializeconnectionop",
    "InitializeConnectionRequestTypedDict": ".initializeconnectionop",
    "InitializeConnectionSecurity": ".initializeconnectionop",
    "InitializeConnectionSecurityTypedDict": ".initializeconnectionop",
    "InlineResponse200": ".inline_response_200",
    "InlineResponse200TypedDict": ".inline_response_200",
    "InlineResponse2001": ".inline_response_200_1",
    "InlineResponse2001TypedDict": ".inline_response_200_1",
    "InlineResponse2002": ".inline_response_200_2",
    "InlineResponse2002TypedDict": ".inline_response_200_2",
    "InlineResponse2003": ".inline_response_200_3",
    "InlineResponse2003Role": ".inline_response_200_3",
    "InlineResponse2003TypedDict": ".inline_response_200_3",
    "InlineResponse2004": ".inline_response_200_4",
    "InlineResponse2004TypedDict": ".inline_response_200_4",
    "InlineResponse2005": ".inline_response_200_5",
    "InlineResponse2005TypedDict": ".inline_response_200_5",
    "InlineResponse2006": ".inline_response_200_6",
    "InlineResponse2006TypedDict": ".inline_response_200_6",
    "InlineResponse2007": ".inline_response_200_7",
    "InlineResponse2007TypedDict": ".inline_response_200_7",
    "Metadata": ".inline_response_200_7",
    "MetadataTypedDict": ".inline_response_200_7",
    "InlineResponse2008": ".inline_response_200_8",
    "InlineResponse2008Metadata": ".inline_response_200_8",
    "InlineResponse2008MetadataTypedDict": ".inline_response_200_8",
    "InlineResponse2008TypedDict": ".inline_response_200_8",
    "Results": ".inline_response_200_8",
    "ResultsTypedDict": ".inline_response_200_8",
    "InlineResponse202": ".inline_response_202",
    "InlineResponse202TypedDict": ".inline_response_202",
    "ListCapabilitiesSecurity": ".listcapabilitiesop",
    "ListCapabilitiesSecurityTypedDict": ".listcapabilitiesop",
    "ListConnectionPromptsRequest": ".listconnectionpromptsop",
    "ListConnectionPromptsRequestTypedDict": ".listconnectionpromptsop",
    "ListConnectionPromptsSecurity": ".listconnectionpromptsop",
    "ListConnectionPromptsSecurityTypedDict": ".listconnectionpromptsop",
    "ListConnectionResourcesRequest": ".listconnectionresourcesop",
    "ListConnectionResourcesRequestTypedDict": ".listconnectionresourcesop",
    "ListConnectionResourcesSecurity": ".listconnectionresourcesop",
    "ListConnectionResourcesSecurityTypedDict": ".listconnectionresourcesop",
    "ListConnectionsSecurity": ".listconnectionsop",
    "ListConnectionsSecurityTypedDict": ".listconnectionsop",
    "ListConnectionToolsRequest": ".listconnectiontoolsop",
    "ListConnectionToolsRequestTypedDict": ".listconnectiontoolsop",
    "ListConnectionToolsSecurity": ".listconnectiontoolsop",
    "ListConnectionToolsSecurityTypedDict": ".listconnectiontoolsop",
    "ListContextsRequest": ".listcontextsop",
    "ListContextsRequestTypedDict": ".listcontextsop",
    "ListContextsSecurity": ".listcontextsop",
    "ListContextsSecurityTypedDict": ".listcontextsop",
    "ListMcpServersRequest": ".listmcpserversop",
    "ListMcpServersRequestTypedDict": ".listmcpserversop",
    "ListMcpServersSecurity": ".listmcpserversop",
    "ListMcpServersSecurityTypedDict": ".listmcpserversop",
    "QueryParamStatus": ".listmcpserversop",
    "ListModelsInContextRequest": ".listmodelsincontextop",
    "ListModelsInContextRequestTypedDict": ".listmodelsincontextop",
    "ListModelsInContextSecurity": ".listmodelsincontextop",
    "ListModelsInContextSecurityTypedDict": ".listmodelsincontextop",
    "ListPromptsSecurity": ".listpromptsop",
    "ListPromptsSecurityTypedDict": ".listpromptsop",
    "ListResourcesRequest": ".listresourcesop",
    "ListResourcesRequestTypedDict": ".listresourcesop",
    "ListResourcesSecurity": ".listresourcesop",
    "ListResourcesSecurityTypedDict": ".listresourcesop",
    "ListResourceTemplatesSecurity": ".listresourcetemplatesop",
    "ListResourceTemplatesSecurityTypedDict": ".listresourcetemplatesop",
    "ListToolsSecurity": ".listtoolsop",
    "ListToolsSecurityTypedDict": ".listtoolsop",
    "Level": ".logging_level_body",
    "LoggingLevelBody": ".logging_level_body",
    "LoggingLevelBodyTypedDict": ".logging_level_body",
    "McpServer": ".mcpserver",
    "McpServerTypedDict": ".mcpserver",
    "Status": ".mcpserver",
    "Model": ".model",
    "ModelTypedDict": ".model",
    "PingConnectionRequest": ".pingconnectionop",
    "PingConnectionRequestTypedDict": ".pingconnectionop",
    "PingConnectionSecurity": ".pingconnectionop",
    "PingConnectionSecurityTypedDict": ".pingconnectionop",
    "PostCompletionSecurity": ".postcompletionop",
    "PostCompletionSecurityTypedDict": ".postcompletionop",
    "PostLogoutSecurity": ".postlogoutop",
    "PostLogoutSecurityTypedDict": ".postlogoutop",
    "PostNotifyOwnerSecurity": ".postnotifyownerop",
    "PostNotifyOwnerSecurityTypedDict": ".postnotifyownerop",
    "PostQuerySecurity": ".postqueryop",
    "PostQuerySecurityTypedDict": ".postqueryop",
    "Prompt": ".prompt",
    "PromptTypedDict": ".prompt",
    "PromptGetBody": ".promptgetbody",
    "PromptGetBodyTypedDict": ".promptgetbody",
    "QueriesBody": ".queries_body",
    "QueriesBodyTypedDict": ".queries_body",
    "ReadConnectionResourceRequest": ".readconnectionresourceop",
    "ReadConnectionResourceRequestTypedDict": ".readconnectionresourceop",
    "ReadConnectionResourceSecurity": ".readconnectionresourceop",
    "ReadConnectionResourceSecurityTypedDict": ".readconnectionresourceop",
    "ReadResourceRequest": ".readresourceop",
    "ReadResourceRequestTypedDict": ".readresourceop",
    "ReadResourceSecurity": ".readresourceop",
    "ReadResourceSecurityTypedDict": ".readresourceop",
    "RegisterMcpServerSecurity": ".registermcpserverop",
    "RegisterMcpServerSecurityTypedDict": ".registermcpserverop",
    "RequestDetails": ".requestdetails",
    "RequestDetailsStatus": ".requestdetails",
    "RequestDetailsTypedDict": ".requestdetails",
    "RequestDetailsEvents": ".requestdetails_events",
    "RequestDetailsEventsTypedDict": ".requestdetails_events",
    "Resource": ".resource",
    "ResourceTypedDict": ".resource",
    "ResourceReadBody": ".resourcereadbody",
    "ResourceReadBodyTypedDict": ".resourcereadbody",
    "ResourceTemplate": ".resourcetemplate",
    "ResourceTemplateTypedDict": ".resourcetemplate",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ServersBody": ".servers_body",
    "ServersBodyTypedDict": ".servers_body",
    "SetLoggingLevelSecurity": ".setlogginglevelop",
    "SetLoggingLevelSecurityTypedDict": ".setlogginglevelop",
    "StartConnectionAuthRequest": ".startconnectionauthop",
    "StartConnectionAuthRequestTypedDict": ".startconnectionauthop",
    "StartConnectionAuthSecurity": ".startconnectionauthop",
    "StartConnectionAuthSecurityTypedDict": ".startconnectionauthop",
    "StreamEventsSecurity": ".streameventsop",
    "StreamEventsSecurityTypedDict": ".streameventsop",
    "SubscribeResourceRequest": ".subscriberesourceop",
    "SubscribeResourceRequestTypedDict": ".subscriberesourceop",
    "SubscribeResourceSecurity": ".subscriberesourceop",
    "SubscribeResourceSecurityTypedDict": ".subscriberesourceop",
    "SystemNotifyOwnerBody": ".system_notifyowner_body",
    "SystemNotifyOwnerBodyTypedDict": ".system_notifyowner_body",
    "Tool": ".tool",
    "ToolTypedDict": ".tool",
    "ToolCallBody": ".toolcallbody",
    "ToolCallBodyTypedDict": ".toolcallbody",
    "ToolCallResult": ".toolcallresult",
    "ToolCallResultTypedDict": ".toolcallresult",
    "TransportOptionsStdio": ".transportoptionsstdio",
    "TransportOptionsStdioTypedDict": ".transportoptionsstdio",
    "TransportOptionsStreamableHTTP": ".transportoptionsstreamablehttp",
    "TransportOptionsStreamableHTTPTypedDict": ".transportoptionsstreamablehttp",
    "UnsubscribeResourceRequest": ".unsubscriberesourceop",
    "UnsubscribeResourceRequestTypedDict": ".unsubscriberesourceop",
    "UnsubscribeResourceSecurity": ".unsubscriberesourceop",
    "UnsubscribeResourceSecurityTypedDict": ".unsubscriberesourceop",
    "Role": ".user",
    "User": ".user",
    "UserTypedDict": ".user",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
