"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CompletionsBodyTypedDict(TypedDict):
    server_id: str
    r"""Target MCP server ID"""
    context_id: str
    r"""Target context ID"""
    model_id: str
    r"""Target model ID"""
    prompt: str
    r"""Prompt string to complete"""
    parameters: NotRequired[Dict[str, Any]]
    r"""Optional parameters for the completion"""


class CompletionsBody(BaseModel):
    server_id: Annotated[str, pydantic.Field(alias="serverId")]
    r"""Target MCP server ID"""

    context_id: Annotated[str, pydantic.Field(alias="contextId")]
    r"""Target context ID"""

    model_id: Annotated[str, pydantic.Field(alias="modelId")]
    r"""Target model ID"""

    prompt: str
    r"""Prompt string to complete"""

    parameters: Optional[Dict[str, Any]] = None
    r"""Optional parameters for the completion"""
