"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from datetime import datetime
from enum import Enum
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Transport(str, Enum):
    r"""Transport type used"""

    STDIO = "stdio"
    STREAMABLE_HTTP = "streamable-http"


class ConnectionStatus(str, Enum):
    r"""Current connection status"""

    INITIALIZING = "initializing"
    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
    ERROR = "error"


class ConnectionTypedDict(TypedDict):
    r"""MCP connection metadata and status"""

    id: NotRequired[str]
    r"""Unique connection identifier"""
    server_id: NotRequired[str]
    r"""MCP server ID connected to"""
    transport: NotRequired[Transport]
    r"""Transport type used"""
    status: NotRequired[ConnectionStatus]
    r"""Current connection status"""
    protocol_version: NotRequired[str]
    r"""Negotiated MCP protocol version"""
    capabilities: NotRequired[List[str]]
    r"""List of server capabilities"""
    created_at: NotRequired[datetime]
    r"""Timestamp when connection was created"""
    updated_at: NotRequired[datetime]
    r"""Timestamp when connection was last updated"""


class Connection(BaseModel):
    r"""MCP connection metadata and status"""

    id: Optional[str] = None
    r"""Unique connection identifier"""

    server_id: Annotated[Optional[str], pydantic.Field(alias="serverId")] = None
    r"""MCP server ID connected to"""

    transport: Optional[Transport] = None
    r"""Transport type used"""

    status: Optional[ConnectionStatus] = None
    r"""Current connection status"""

    protocol_version: Annotated[
        Optional[str], pydantic.Field(alias="protocolVersion")
    ] = None
    r"""Negotiated MCP protocol version"""

    capabilities: Optional[List[str]] = None
    r"""List of server capabilities"""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""Timestamp when connection was created"""

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
    r"""Timestamp when connection was last updated"""
