"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ConnectionInitializeResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    protocol_version: NotRequired[str]
    server_info: NotRequired[Dict[str, Any]]
    capabilities: NotRequired[Dict[str, Any]]
    instructions: NotRequired[Nullable[str]]


class ConnectionInitializeResponse(BaseModel):
    success: Optional[bool] = None

    protocol_version: Annotated[
        Optional[str], pydantic.Field(alias="protocolVersion")
    ] = None

    server_info: Annotated[
        Optional[Dict[str, Any]], pydantic.Field(alias="serverInfo")
    ] = None

    capabilities: Optional[Dict[str, Any]] = None

    instructions: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "success",
            "protocolVersion",
            "serverInfo",
            "capabilities",
            "instructions",
        ]
        nullable_fields = ["instructions"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
