"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ContextTypedDict(TypedDict):
    r"""MCP server context information"""

    id: NotRequired[str]
    r"""Unique context identifier"""
    server_id: NotRequired[str]
    r"""Associated MCP server ID"""
    name: NotRequired[str]
    r"""Context name"""
    description: NotRequired[Nullable[str]]
    r"""Optional context description"""


class Context(BaseModel):
    r"""MCP server context information"""

    id: Optional[str] = None
    r"""Unique context identifier"""

    server_id: Annotated[Optional[str], pydantic.Field(alias="serverId")] = None
    r"""Associated MCP server ID"""

    name: Optional[str] = None
    r"""Context name"""

    description: OptionalNullable[str] = UNSET
    r"""Optional context description"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "serverId", "name", "description"]
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
