"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MetadataTypedDict(TypedDict):
    r"""Additional metadata about the completion"""


class Metadata(BaseModel):
    r"""Additional metadata about the completion"""


class InlineResponse2007TypedDict(TypedDict):
    completion: NotRequired[str]
    r"""Completion text"""
    metadata: NotRequired[MetadataTypedDict]
    r"""Additional metadata about the completion"""


class InlineResponse2007(BaseModel):
    completion: Optional[str] = None
    r"""Completion text"""

    metadata: Optional[Metadata] = None
    r"""Additional metadata about the completion"""
