"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InlineResponse2006TypedDict(TypedDict):
    unsubscribed: NotRequired[bool]


class InlineResponse2006(BaseModel):
    unsubscribed: Optional[bool] = None
