"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from cassie_marie_mcp_hub_api_python.utils import FieldMetadata, SecurityMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListConnectionsSecurityTypedDict(TypedDict):
    app_session_cookie: NotRequired[str]
    bearer_auth: NotRequired[str]


class ListConnectionsSecurity(BaseModel):
    app_session_cookie: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="cookie",
                field_name="app_session_id",
            )
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None
