"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from enum import Enum
from typing_extensions import TypedDict


class Level(str, Enum):
    r"""Logging level to set"""

    DEBUG = "debug"
    INFO = "info"
    WARN = "warn"
    ERROR = "error"
    FATAL = "fatal"


class LoggingLevelBodyTypedDict(TypedDict):
    level: Level
    r"""Logging level to set"""


class LoggingLevelBody(BaseModel):
    level: Level
    r"""Logging level to set"""
