"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolCallResultTypedDict(TypedDict):
    is_error: NotRequired[bool]
    content: NotRequired[List[Dict[str, Any]]]
    structured_content: NotRequired[Dict[str, Any]]
    metadata: NotRequired[Dict[str, Any]]


class ToolCallResult(BaseModel):
    is_error: Annotated[Optional[bool], pydantic.Field(alias="isError")] = None

    content: Optional[List[Dict[str, Any]]] = None

    structured_content: Annotated[
        Optional[Dict[str, Any]], pydantic.Field(alias="structuredContent")
    ] = None

    metadata: Optional[Dict[str, Any]] = None
