"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cassie_marie_mcp_hub_api_python.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class TransportOptionsStdioTypedDict(TypedDict):
    r"""Transport options for stdio-based MCP servers."""

    command: str
    r"""Executable used to launch the MCP server process."""
    args: NotRequired[List[str]]
    r"""Optional command-line arguments."""
    env: NotRequired[Dict[str, str]]
    r"""Environment variables passed to the child process."""
    cwd: NotRequired[str]
    r"""Working directory for the child process."""


class TransportOptionsStdio(BaseModel):
    r"""Transport options for stdio-based MCP servers."""

    command: str
    r"""Executable used to launch the MCP server process."""

    args: Optional[List[str]] = None
    r"""Optional command-line arguments."""

    env: Optional[Dict[str, str]] = None
    r"""Environment variables passed to the child process."""

    cwd: Optional[str] = None
    r"""Working directory for the child process."""
