/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.models.components.ToolCallBody;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class CallConnectionToolRequest {

    /**
     * Unique identifier of the connection.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connectionId")
    private String connectionId;

    /**
     * Name of the MCP tool to invoke.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=toolName")
    private String toolName;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private ToolCallBody toolCallBody;

    @JsonCreator
    public CallConnectionToolRequest(
            String connectionId,
            String toolName,
            ToolCallBody toolCallBody) {
        Utils.checkNotNull(connectionId, "connectionId");
        Utils.checkNotNull(toolName, "toolName");
        Utils.checkNotNull(toolCallBody, "toolCallBody");
        this.connectionId = connectionId;
        this.toolName = toolName;
        this.toolCallBody = toolCallBody;
    }

    /**
     * Unique identifier of the connection.
     */
    @JsonIgnore
    public String connectionId() {
        return connectionId;
    }

    /**
     * Name of the MCP tool to invoke.
     */
    @JsonIgnore
    public String toolName() {
        return toolName;
    }

    @JsonIgnore
    public ToolCallBody toolCallBody() {
        return toolCallBody;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier of the connection.
     */
    public CallConnectionToolRequest withConnectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    /**
     * Name of the MCP tool to invoke.
     */
    public CallConnectionToolRequest withToolName(String toolName) {
        Utils.checkNotNull(toolName, "toolName");
        this.toolName = toolName;
        return this;
    }

    public CallConnectionToolRequest withToolCallBody(ToolCallBody toolCallBody) {
        Utils.checkNotNull(toolCallBody, "toolCallBody");
        this.toolCallBody = toolCallBody;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CallConnectionToolRequest other = (CallConnectionToolRequest) o;
        return 
            Objects.deepEquals(this.connectionId, other.connectionId) &&
            Objects.deepEquals(this.toolName, other.toolName) &&
            Objects.deepEquals(this.toolCallBody, other.toolCallBody);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            connectionId,
            toolName,
            toolCallBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CallConnectionToolRequest.class,
                "connectionId", connectionId,
                "toolName", toolName,
                "toolCallBody", toolCallBody);
    }
    
    public final static class Builder {
 
        private String connectionId;
 
        private String toolName;
 
        private ToolCallBody toolCallBody;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the connection.
         */
        public Builder connectionId(String connectionId) {
            Utils.checkNotNull(connectionId, "connectionId");
            this.connectionId = connectionId;
            return this;
        }

        /**
         * Name of the MCP tool to invoke.
         */
        public Builder toolName(String toolName) {
            Utils.checkNotNull(toolName, "toolName");
            this.toolName = toolName;
            return this;
        }

        public Builder toolCallBody(ToolCallBody toolCallBody) {
            Utils.checkNotNull(toolCallBody, "toolCallBody");
            this.toolCallBody = toolCallBody;
            return this;
        }
        
        public CallConnectionToolRequest build() {
            return new CallConnectionToolRequest(
                connectionId,
                toolName,
                toolCallBody);
        }
    }
}
