/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class GetConnectionCapabilitiesRequestBuilder {

    private GetConnectionCapabilitiesSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallGetConnectionCapabilities sdk;

    public GetConnectionCapabilitiesRequestBuilder(SDKMethodInterfaces.MethodCallGetConnectionCapabilities sdk) {
        this.sdk = sdk;
    }

    public GetConnectionCapabilitiesRequestBuilder security(GetConnectionCapabilitiesSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public GetConnectionCapabilitiesRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public GetConnectionCapabilitiesResponse call() throws Exception {

        return sdk.getConnectionCapabilities(
            security,
            connectionId);
    }
}
