/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import org.openapis.openapi.utils.Utils;

public class GetCurrentUserRequestBuilder {

    private GetCurrentUserSecurity security;
    private final SDKMethodInterfaces.MethodCallGetCurrentUser sdk;

    public GetCurrentUserRequestBuilder(SDKMethodInterfaces.MethodCallGetCurrentUser sdk) {
        this.sdk = sdk;
    }

    public GetCurrentUserRequestBuilder security(GetCurrentUserSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public GetCurrentUserResponse call() throws Exception {

        return sdk.getCurrentUser(
            security);
    }
}
