/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class GetConnectionAuthStatusRequestBuilder {

    private GetConnectionAuthStatusSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallGetConnectionAuthStatus sdk;

    public GetConnectionAuthStatusRequestBuilder(SDKMethodInterfaces.MethodCallGetConnectionAuthStatus sdk) {
        this.sdk = sdk;
    }

    public GetConnectionAuthStatusRequestBuilder security(GetConnectionAuthStatusSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public GetConnectionAuthStatusRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public GetConnectionAuthStatusResponse call() throws Exception {

        return sdk.getConnectionAuthStatus(
            security,
            connectionId);
    }
}
