/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class GetConnectionByIdRequestBuilder {

    private GetConnectionByIdSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallGetConnectionById sdk;

    public GetConnectionByIdRequestBuilder(SDKMethodInterfaces.MethodCallGetConnectionById sdk) {
        this.sdk = sdk;
    }

    public GetConnectionByIdRequestBuilder security(GetConnectionByIdSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public GetConnectionByIdRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public GetConnectionByIdResponse call() throws Exception {

        return sdk.getConnectionById(
            security,
            connectionId);
    }
}
