/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class GetPromptByIdRequest {

    /**
     * Unique identifier of the prompt
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=promptId")
    private String promptId;

    @JsonCreator
    public GetPromptByIdRequest(
            String promptId) {
        Utils.checkNotNull(promptId, "promptId");
        this.promptId = promptId;
    }

    /**
     * Unique identifier of the prompt
     */
    @JsonIgnore
    public String promptId() {
        return promptId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier of the prompt
     */
    public GetPromptByIdRequest withPromptId(String promptId) {
        Utils.checkNotNull(promptId, "promptId");
        this.promptId = promptId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPromptByIdRequest other = (GetPromptByIdRequest) o;
        return 
            Objects.deepEquals(this.promptId, other.promptId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            promptId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPromptByIdRequest.class,
                "promptId", promptId);
    }
    
    public final static class Builder {
 
        private String promptId;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the prompt
         */
        public Builder promptId(String promptId) {
            Utils.checkNotNull(promptId, "promptId");
            this.promptId = promptId;
            return this;
        }
        
        public GetPromptByIdRequest build() {
            return new GetPromptByIdRequest(
                promptId);
        }
    }
}
