/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class GetRequestDetailsRequest {

    /**
     * Unique identifier of the request
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=requestId")
    private String requestId;

    @JsonCreator
    public GetRequestDetailsRequest(
            String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
    }

    /**
     * Unique identifier of the request
     */
    @JsonIgnore
    public String requestId() {
        return requestId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier of the request
     */
    public GetRequestDetailsRequest withRequestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRequestDetailsRequest other = (GetRequestDetailsRequest) o;
        return 
            Objects.deepEquals(this.requestId, other.requestId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            requestId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetRequestDetailsRequest.class,
                "requestId", requestId);
    }
    
    public final static class Builder {
 
        private String requestId;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the request
         */
        public Builder requestId(String requestId) {
            Utils.checkNotNull(requestId, "requestId");
            this.requestId = requestId;
            return this;
        }
        
        public GetRequestDetailsRequest build() {
            return new GetRequestDetailsRequest(
                requestId);
        }
    }
}
