/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Double;
import java.lang.Exception;
import org.openapis.openapi.utils.Utils;

public class GetSystemHealthRequestBuilder {

    private Double timestamp;
    private final SDKMethodInterfaces.MethodCallGetSystemHealth sdk;

    public GetSystemHealthRequestBuilder(SDKMethodInterfaces.MethodCallGetSystemHealth sdk) {
        this.sdk = sdk;
    }

    public GetSystemHealthRequestBuilder timestamp(double timestamp) {
        Utils.checkNotNull(timestamp, "timestamp");
        this.timestamp = timestamp;
        return this;
    }

    public GetSystemHealthResponse call() throws Exception {

        return sdk.getSystemHealth(
            timestamp);
    }
}
