/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import org.openapis.openapi.utils.Utils;

public class ListResourceTemplatesRequestBuilder {

    private ListResourceTemplatesSecurity security;
    private final SDKMethodInterfaces.MethodCallListResourceTemplates sdk;

    public ListResourceTemplatesRequestBuilder(SDKMethodInterfaces.MethodCallListResourceTemplates sdk) {
        this.sdk = sdk;
    }

    public ListResourceTemplatesRequestBuilder security(ListResourceTemplatesSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public ListResourceTemplatesResponse call() throws Exception {

        return sdk.listResourceTemplates(
            security);
    }
}
