/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import org.openapis.openapi.utils.Utils;

public class ListPromptsRequestBuilder {

    private ListPromptsSecurity security;
    private final SDKMethodInterfaces.MethodCallListPrompts sdk;

    public ListPromptsRequestBuilder(SDKMethodInterfaces.MethodCallListPrompts sdk) {
        this.sdk = sdk;
    }

    public ListPromptsRequestBuilder security(ListPromptsSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public ListPromptsResponse call() throws Exception {

        return sdk.listPrompts(
            security);
    }
}
