/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListResourcesRequestBuilder {

    private ListResourcesSecurity security;
    private Optional<String> serverId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListResources sdk;

    public ListResourcesRequestBuilder(SDKMethodInterfaces.MethodCallListResources sdk) {
        this.sdk = sdk;
    }

    public ListResourcesRequestBuilder security(ListResourcesSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }
                
    public ListResourcesRequestBuilder serverId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = Optional.of(serverId);
        return this;
    }

    public ListResourcesRequestBuilder serverId(Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    public ListResourcesResponse call() throws Exception {

        return sdk.listResources(
            security,
            serverId);
    }
}
