/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class ListConnectionResourcesRequestBuilder {

    private ListConnectionResourcesSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallListConnectionResources sdk;

    public ListConnectionResourcesRequestBuilder(SDKMethodInterfaces.MethodCallListConnectionResources sdk) {
        this.sdk = sdk;
    }

    public ListConnectionResourcesRequestBuilder security(ListConnectionResourcesSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public ListConnectionResourcesRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public ListConnectionResourcesResponse call() throws Exception {

        return sdk.listConnectionResources(
            security,
            connectionId);
    }
}
