/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class ListResourcesRequest {

    /**
     * Filter resources by MCP server ID
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=serverId")
    private Optional<String> serverId;

    @JsonCreator
    public ListResourcesRequest(
            Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
    }
    
    public ListResourcesRequest() {
        this(Optional.empty());
    }

    /**
     * Filter resources by MCP server ID
     */
    @JsonIgnore
    public Optional<String> serverId() {
        return serverId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Filter resources by MCP server ID
     */
    public ListResourcesRequest withServerId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = Optional.ofNullable(serverId);
        return this;
    }

    /**
     * Filter resources by MCP server ID
     */
    public ListResourcesRequest withServerId(Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListResourcesRequest other = (ListResourcesRequest) o;
        return 
            Objects.deepEquals(this.serverId, other.serverId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            serverId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListResourcesRequest.class,
                "serverId", serverId);
    }
    
    public final static class Builder {
 
        private Optional<String> serverId = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Filter resources by MCP server ID
         */
        public Builder serverId(String serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = Optional.ofNullable(serverId);
            return this;
        }

        /**
         * Filter resources by MCP server ID
         */
        public Builder serverId(Optional<String> serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = serverId;
            return this;
        }
        
        public ListResourcesRequest build() {
            return new ListResourcesRequest(
                serverId);
        }
    }
}
