/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class ListConnectionToolsRequestBuilder {

    private ListConnectionToolsSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallListConnectionTools sdk;

    public ListConnectionToolsRequestBuilder(SDKMethodInterfaces.MethodCallListConnectionTools sdk) {
        this.sdk = sdk;
    }

    public ListConnectionToolsRequestBuilder security(ListConnectionToolsSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public ListConnectionToolsRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public ListConnectionToolsResponse call() throws Exception {

        return sdk.listConnectionTools(
            security,
            connectionId);
    }
}
