/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListContextsRequestBuilder {

    private ListContextsSecurity security;
    private Optional<String> serverId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListContexts sdk;

    public ListContextsRequestBuilder(SDKMethodInterfaces.MethodCallListContexts sdk) {
        this.sdk = sdk;
    }

    public ListContextsRequestBuilder security(ListContextsSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }
                
    public ListContextsRequestBuilder serverId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = Optional.of(serverId);
        return this;
    }

    public ListContextsRequestBuilder serverId(Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    public ListContextsResponse call() throws Exception {

        return sdk.listContexts(
            security,
            serverId);
    }
}
