/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class PingConnectionRequestBuilder {

    private PingConnectionSecurity security;
    private String connectionId;
    private final SDKMethodInterfaces.MethodCallPingConnection sdk;

    public PingConnectionRequestBuilder(SDKMethodInterfaces.MethodCallPingConnection sdk) {
        this.sdk = sdk;
    }

    public PingConnectionRequestBuilder security(PingConnectionSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public PingConnectionRequestBuilder connectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public PingConnectionResponse call() throws Exception {

        return sdk.pingConnection(
            security,
            connectionId);
    }
}
