/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.models.components.ResourceReadBody;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class ReadConnectionResourceRequest {

    /**
     * Unique identifier of the connection.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connectionId")
    private String connectionId;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private ResourceReadBody resourceReadBody;

    @JsonCreator
    public ReadConnectionResourceRequest(
            String connectionId,
            ResourceReadBody resourceReadBody) {
        Utils.checkNotNull(connectionId, "connectionId");
        Utils.checkNotNull(resourceReadBody, "resourceReadBody");
        this.connectionId = connectionId;
        this.resourceReadBody = resourceReadBody;
    }

    /**
     * Unique identifier of the connection.
     */
    @JsonIgnore
    public String connectionId() {
        return connectionId;
    }

    @JsonIgnore
    public ResourceReadBody resourceReadBody() {
        return resourceReadBody;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier of the connection.
     */
    public ReadConnectionResourceRequest withConnectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    public ReadConnectionResourceRequest withResourceReadBody(ResourceReadBody resourceReadBody) {
        Utils.checkNotNull(resourceReadBody, "resourceReadBody");
        this.resourceReadBody = resourceReadBody;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReadConnectionResourceRequest other = (ReadConnectionResourceRequest) o;
        return 
            Objects.deepEquals(this.connectionId, other.connectionId) &&
            Objects.deepEquals(this.resourceReadBody, other.resourceReadBody);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            connectionId,
            resourceReadBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ReadConnectionResourceRequest.class,
                "connectionId", connectionId,
                "resourceReadBody", resourceReadBody);
    }
    
    public final static class Builder {
 
        private String connectionId;
 
        private ResourceReadBody resourceReadBody;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the connection.
         */
        public Builder connectionId(String connectionId) {
            Utils.checkNotNull(connectionId, "connectionId");
            this.connectionId = connectionId;
            return this;
        }

        public Builder resourceReadBody(ResourceReadBody resourceReadBody) {
            Utils.checkNotNull(resourceReadBody, "resourceReadBody");
            this.resourceReadBody = resourceReadBody;
            return this;
        }
        
        public ReadConnectionResourceRequest build() {
            return new ReadConnectionResourceRequest(
                connectionId,
                resourceReadBody);
        }
    }
}
