/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.models.components.McpServer;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;

public class RegisterMcpServerResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * MCP server registered successfully
     */
    private Optional<? extends McpServer> mcpServer;

    @JsonCreator
    public RegisterMcpServerResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends McpServer> mcpServer) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(mcpServer, "mcpServer");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.mcpServer = mcpServer;
    }
    
    public RegisterMcpServerResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * MCP server registered successfully
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<McpServer> mcpServer() {
        return (Optional<McpServer>) mcpServer;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public RegisterMcpServerResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public RegisterMcpServerResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public RegisterMcpServerResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * MCP server registered successfully
     */
    public RegisterMcpServerResponse withMcpServer(McpServer mcpServer) {
        Utils.checkNotNull(mcpServer, "mcpServer");
        this.mcpServer = Optional.ofNullable(mcpServer);
        return this;
    }

    /**
     * MCP server registered successfully
     */
    public RegisterMcpServerResponse withMcpServer(Optional<? extends McpServer> mcpServer) {
        Utils.checkNotNull(mcpServer, "mcpServer");
        this.mcpServer = mcpServer;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RegisterMcpServerResponse other = (RegisterMcpServerResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.mcpServer, other.mcpServer);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            mcpServer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RegisterMcpServerResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "mcpServer", mcpServer);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends McpServer> mcpServer = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * MCP server registered successfully
         */
        public Builder mcpServer(McpServer mcpServer) {
            Utils.checkNotNull(mcpServer, "mcpServer");
            this.mcpServer = Optional.ofNullable(mcpServer);
            return this;
        }

        /**
         * MCP server registered successfully
         */
        public Builder mcpServer(Optional<? extends McpServer> mcpServer) {
            Utils.checkNotNull(mcpServer, "mcpServer");
            this.mcpServer = mcpServer;
            return this;
        }
        
        public RegisterMcpServerResponse build() {
            return new RegisterMcpServerResponse(
                contentType,
                statusCode,
                rawResponse,
                mcpServer);
        }
    }
}
