/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import org.openapis.openapi.models.components.LoggingLevelBody;
import org.openapis.openapi.utils.Utils;

public class SetLoggingLevelRequestBuilder {

    private LoggingLevelBody request;
    private SetLoggingLevelSecurity security;
    private final SDKMethodInterfaces.MethodCallSetLoggingLevel sdk;

    public SetLoggingLevelRequestBuilder(SDKMethodInterfaces.MethodCallSetLoggingLevel sdk) {
        this.sdk = sdk;
    }

    public SetLoggingLevelRequestBuilder request(LoggingLevelBody request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public SetLoggingLevelRequestBuilder security(SetLoggingLevelSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public SetLoggingLevelResponse call() throws Exception {

        return sdk.setLoggingLevel(
            request,
            security);
    }
}
