/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.models.components.AuthStartResponse;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;

public class StartConnectionAuthResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Remote auth flow started
     */
    private Optional<? extends AuthStartResponse> authStartResponse;

    @JsonCreator
    public StartConnectionAuthResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends AuthStartResponse> authStartResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(authStartResponse, "authStartResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.authStartResponse = authStartResponse;
    }
    
    public StartConnectionAuthResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Remote auth flow started
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthStartResponse> authStartResponse() {
        return (Optional<AuthStartResponse>) authStartResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public StartConnectionAuthResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public StartConnectionAuthResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public StartConnectionAuthResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Remote auth flow started
     */
    public StartConnectionAuthResponse withAuthStartResponse(AuthStartResponse authStartResponse) {
        Utils.checkNotNull(authStartResponse, "authStartResponse");
        this.authStartResponse = Optional.ofNullable(authStartResponse);
        return this;
    }

    /**
     * Remote auth flow started
     */
    public StartConnectionAuthResponse withAuthStartResponse(Optional<? extends AuthStartResponse> authStartResponse) {
        Utils.checkNotNull(authStartResponse, "authStartResponse");
        this.authStartResponse = authStartResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartConnectionAuthResponse other = (StartConnectionAuthResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.authStartResponse, other.authStartResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            authStartResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartConnectionAuthResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "authStartResponse", authStartResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends AuthStartResponse> authStartResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Remote auth flow started
         */
        public Builder authStartResponse(AuthStartResponse authStartResponse) {
            Utils.checkNotNull(authStartResponse, "authStartResponse");
            this.authStartResponse = Optional.ofNullable(authStartResponse);
            return this;
        }

        /**
         * Remote auth flow started
         */
        public Builder authStartResponse(Optional<? extends AuthStartResponse> authStartResponse) {
            Utils.checkNotNull(authStartResponse, "authStartResponse");
            this.authStartResponse = authStartResponse;
            return this;
        }
        
        public StartConnectionAuthResponse build() {
            return new StartConnectionAuthResponse(
                contentType,
                statusCode,
                rawResponse,
                authStartResponse);
        }
    }
}
