/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import org.openapis.openapi.utils.Utils;

public class StreamEventsRequestBuilder {

    private StreamEventsSecurity security;
    private final SDKMethodInterfaces.MethodCallStreamEvents sdk;

    public StreamEventsRequestBuilder(SDKMethodInterfaces.MethodCallStreamEvents sdk) {
        this.sdk = sdk;
    }

    public StreamEventsRequestBuilder security(StreamEventsSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public StreamEventsResponse call() throws Exception {

        return sdk.streamEvents(
            security);
    }
}
