/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class SubscribeResourceRequest {

    /**
     * Unique identifier of the resource
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=resourceId")
    private String resourceId;

    @JsonCreator
    public SubscribeResourceRequest(
            String resourceId) {
        Utils.checkNotNull(resourceId, "resourceId");
        this.resourceId = resourceId;
    }

    /**
     * Unique identifier of the resource
     */
    @JsonIgnore
    public String resourceId() {
        return resourceId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique identifier of the resource
     */
    public SubscribeResourceRequest withResourceId(String resourceId) {
        Utils.checkNotNull(resourceId, "resourceId");
        this.resourceId = resourceId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribeResourceRequest other = (SubscribeResourceRequest) o;
        return 
            Objects.deepEquals(this.resourceId, other.resourceId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            resourceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribeResourceRequest.class,
                "resourceId", resourceId);
    }
    
    public final static class Builder {
 
        private String resourceId;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the resource
         */
        public Builder resourceId(String resourceId) {
            Utils.checkNotNull(resourceId, "resourceId");
            this.resourceId = resourceId;
            return this;
        }
        
        public SubscribeResourceRequest build() {
            return new SubscribeResourceRequest(
                resourceId);
        }
    }
}
