/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

public class UnsubscribeResourceRequestBuilder {

    private UnsubscribeResourceSecurity security;
    private String resourceId;
    private final SDKMethodInterfaces.MethodCallUnsubscribeResource sdk;

    public UnsubscribeResourceRequestBuilder(SDKMethodInterfaces.MethodCallUnsubscribeResource sdk) {
        this.sdk = sdk;
    }

    public UnsubscribeResourceRequestBuilder security(UnsubscribeResourceSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public UnsubscribeResourceRequestBuilder resourceId(String resourceId) {
        Utils.checkNotNull(resourceId, "resourceId");
        this.resourceId = resourceId;
        return this;
    }

    public UnsubscribeResourceResponse call() throws Exception {

        return sdk.unsubscribeResource(
            security,
            resourceId);
    }
}
