/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsCreateConnection } from "../funcs/connectionsCreateConnection.js";
import { connectionsDeleteConnection } from "../funcs/connectionsDeleteConnection.js";
import { connectionsGetConnectionById } from "../funcs/connectionsGetConnectionById.js";
import { connectionsListConnections } from "../funcs/connectionsListConnections.js";
import { connectionsPingConnection } from "../funcs/connectionsPingConnection.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Connections extends ClientSDK {
  /**
   * List all MCP connections for the authenticated user
   *
   * @remarks
   * List all MCP connections for the authenticated user
   */
  async listConnections(
    security: operations.ListConnectionsSecurity,
    options?: RequestOptions,
  ): Promise<Array<components.Connection>> {
    return unwrapAsync(connectionsListConnections(
      this,
      security,
      options,
    ));
  }

  /**
   * Create and initialize a new MCP connection
   *
   * @remarks
   * Create and initialize a new MCP connection
   */
  async createConnection(
    security: operations.CreateConnectionSecurity,
    request: components.ConnectionsBody,
    options?: RequestOptions,
  ): Promise<components.Connection> {
    return unwrapAsync(connectionsCreateConnection(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get details and status of a specific MCP connection
   *
   * @remarks
   * Get details and status of a specific MCP connection
   */
  async getConnectionById(
    security: operations.GetConnectionByIdSecurity,
    request: operations.GetConnectionByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Connection> {
    return unwrapAsync(connectionsGetConnectionById(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Disconnect and remove an MCP connection
   *
   * @remarks
   * Disconnect and remove an MCP connection
   */
  async deleteConnection(
    security: operations.DeleteConnectionSecurity,
    request: operations.DeleteConnectionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(connectionsDeleteConnection(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Send a ping to the MCP server via the connection
   *
   * @remarks
   * Send a ping to the MCP server via the connection
   */
  async pingConnection(
    security: operations.PingConnectionSecurity,
    request: operations.PingConnectionRequest,
    options?: RequestOptions,
  ): Promise<components.InlineResponse2004> {
    return unwrapAsync(connectionsPingConnection(
      this,
      security,
      request,
      options,
    ));
  }
}
