/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contextsGetContextById } from "../funcs/contextsGetContextById.js";
import { contextsListContexts } from "../funcs/contextsListContexts.js";
import { contextsListModelsInContext } from "../funcs/contextsListModelsInContext.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contexts extends ClientSDK {
  /**
   * List available contexts from connected MCP servers
   *
   * @remarks
   * List available contexts from connected MCP servers
   */
  async listContexts(
    security: operations.ListContextsSecurity,
    request: operations.ListContextsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.Context>> {
    return unwrapAsync(contextsListContexts(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get details of a specific context
   *
   * @remarks
   * Get details of a specific context
   */
  async getContextById(
    security: operations.GetContextByIdSecurity,
    request: operations.GetContextByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Context> {
    return unwrapAsync(contextsGetContextById(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * List models available in a specific context
   *
   * @remarks
   * List models available in a specific context
   */
  async listModelsInContext(
    security: operations.ListModelsInContextSecurity,
    request: operations.ListModelsInContextRequest,
    options?: RequestOptions,
  ): Promise<Array<components.Model>> {
    return unwrapAsync(contextsListModelsInContext(
      this,
      security,
      request,
      options,
    ));
  }
}
