/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetRequestDetails } from "../funcs/eventsGetRequestDetails.js";
import { eventsStreamEvents } from "../funcs/eventsStreamEvents.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * Stream live events and notifications (SSE or WebSocket)
   *
   * @remarks
   * Stream live events and notifications (SSE or WebSocket)
   */
  async streamEvents(
    security: operations.StreamEventsSecurity,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(eventsStreamEvents(
      this,
      security,
      options,
    ));
  }

  /**
   * Get details and history of a specific request
   *
   * @remarks
   * Get details and history of a specific request
   */
  async getRequestDetails(
    security: operations.GetRequestDetailsSecurity,
    request: operations.GetRequestDetailsRequest,
    options?: RequestOptions,
  ): Promise<components.RequestDetails> {
    return unwrapAsync(eventsGetRequestDetails(
      this,
      security,
      request,
      options,
    ));
  }
}
