/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auth } from "./auth.js";
import { Capabilities } from "./capabilities.js";
import { Completions } from "./completions.js";
import { ConnectionAuth } from "./connectionauth.js";
import { Connections } from "./connections.js";
import { Contexts } from "./contexts.js";
import { Events } from "./events.js";
import { Logging } from "./logging.js";
import { Prompts } from "./prompts.js";
import { Queries } from "./queries.js";
import { Resources } from "./resources.js";
import { Runtime } from "./runtime.js";
import { Servers } from "./servers.js";
import { System } from "./system.js";
import { Tools } from "./tools.js";

export class McpHubApiTypescript extends ClientSDK {
  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }

  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _servers?: Servers;
  get servers(): Servers {
    return (this._servers ??= new Servers(this._options));
  }

  private _connections?: Connections;
  get connections(): Connections {
    return (this._connections ??= new Connections(this._options));
  }

  private _capabilities?: Capabilities;
  get capabilities(): Capabilities {
    return (this._capabilities ??= new Capabilities(this._options));
  }

  private _tools?: Tools;
  get tools(): Tools {
    return (this._tools ??= new Tools(this._options));
  }

  private _resources?: Resources;
  get resources(): Resources {
    return (this._resources ??= new Resources(this._options));
  }

  private _prompts?: Prompts;
  get prompts(): Prompts {
    return (this._prompts ??= new Prompts(this._options));
  }

  private _completions?: Completions;
  get completions(): Completions {
    return (this._completions ??= new Completions(this._options));
  }

  private _logging?: Logging;
  get logging(): Logging {
    return (this._logging ??= new Logging(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _queries?: Queries;
  get queries(): Queries {
    return (this._queries ??= new Queries(this._options));
  }

  private _contexts?: Contexts;
  get contexts(): Contexts {
    return (this._contexts ??= new Contexts(this._options));
  }

  private _runtime?: Runtime;
  get runtime(): Runtime {
    return (this._runtime ??= new Runtime(this._options));
  }

  private _connectionAuth?: ConnectionAuth;
  get connectionAuth(): ConnectionAuth {
    return (this._connectionAuth ??= new ConnectionAuth(this._options));
  }
}
