/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversGetMcpServerById } from "../funcs/serversGetMcpServerById.js";
import { serversListMcpServers } from "../funcs/serversListMcpServers.js";
import { serversRegisterMcpServer } from "../funcs/serversRegisterMcpServer.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Servers extends ClientSDK {
  /**
   * List available MCP servers
   *
   * @remarks
   * Returns MCP servers that the current user can browse or connect to.
   */
  async listMcpServers(
    security: operations.ListMcpServersSecurity,
    request: operations.ListMcpServersRequest,
    options?: RequestOptions,
  ): Promise<Array<components.McpServer>> {
    return unwrapAsync(serversListMcpServers(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Register a new MCP server (admin only)
   *
   * @remarks
   * Register a new MCP server (admin only)
   */
  async registerMcpServer(
    security: operations.RegisterMcpServerSecurity,
    request: components.ServersBody,
    options?: RequestOptions,
  ): Promise<components.McpServer> {
    return unwrapAsync(serversRegisterMcpServer(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get details of a specific MCP server
   *
   * @remarks
   * Get details of a specific MCP server
   */
  async getMcpServerById(
    security: operations.GetMcpServerByIdSecurity,
    request: operations.GetMcpServerByIdRequest,
    options?: RequestOptions,
  ): Promise<components.McpServer> {
    return unwrapAsync(serversGetMcpServerById(
      this,
      security,
      request,
      options,
    ));
  }
}
