/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteConnectionSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type DeleteConnectionRequest = {
  /**
   * Unique identifier of the connection
   */
  connectionId: string;
};

/** @internal */
export const DeleteConnectionSecurity$inboundSchema: z.ZodType<
  DeleteConnectionSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type DeleteConnectionSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const DeleteConnectionSecurity$outboundSchema: z.ZodType<
  DeleteConnectionSecurity$Outbound,
  z.ZodTypeDef,
  DeleteConnectionSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteConnectionSecurity$ {
  /** @deprecated use `DeleteConnectionSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteConnectionSecurity$inboundSchema;
  /** @deprecated use `DeleteConnectionSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteConnectionSecurity$outboundSchema;
  /** @deprecated use `DeleteConnectionSecurity$Outbound` instead. */
  export type Outbound = DeleteConnectionSecurity$Outbound;
}

export function deleteConnectionSecurityToJSON(
  deleteConnectionSecurity: DeleteConnectionSecurity,
): string {
  return JSON.stringify(
    DeleteConnectionSecurity$outboundSchema.parse(deleteConnectionSecurity),
  );
}

export function deleteConnectionSecurityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConnectionSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConnectionSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConnectionSecurity' from JSON`,
  );
}

/** @internal */
export const DeleteConnectionRequest$inboundSchema: z.ZodType<
  DeleteConnectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
});

/** @internal */
export type DeleteConnectionRequest$Outbound = {
  connectionId: string;
};

/** @internal */
export const DeleteConnectionRequest$outboundSchema: z.ZodType<
  DeleteConnectionRequest$Outbound,
  z.ZodTypeDef,
  DeleteConnectionRequest
> = z.object({
  connectionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteConnectionRequest$ {
  /** @deprecated use `DeleteConnectionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteConnectionRequest$inboundSchema;
  /** @deprecated use `DeleteConnectionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteConnectionRequest$outboundSchema;
  /** @deprecated use `DeleteConnectionRequest$Outbound` instead. */
  export type Outbound = DeleteConnectionRequest$Outbound;
}

export function deleteConnectionRequestToJSON(
  deleteConnectionRequest: DeleteConnectionRequest,
): string {
  return JSON.stringify(
    DeleteConnectionRequest$outboundSchema.parse(deleteConnectionRequest),
  );
}

export function deleteConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConnectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConnectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConnectionRequest' from JSON`,
  );
}
