/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetConnectionByIdSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type GetConnectionByIdRequest = {
  /**
   * Unique identifier of the connection
   */
  connectionId: string;
};

/** @internal */
export const GetConnectionByIdSecurity$inboundSchema: z.ZodType<
  GetConnectionByIdSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetConnectionByIdSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetConnectionByIdSecurity$outboundSchema: z.ZodType<
  GetConnectionByIdSecurity$Outbound,
  z.ZodTypeDef,
  GetConnectionByIdSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConnectionByIdSecurity$ {
  /** @deprecated use `GetConnectionByIdSecurity$inboundSchema` instead. */
  export const inboundSchema = GetConnectionByIdSecurity$inboundSchema;
  /** @deprecated use `GetConnectionByIdSecurity$outboundSchema` instead. */
  export const outboundSchema = GetConnectionByIdSecurity$outboundSchema;
  /** @deprecated use `GetConnectionByIdSecurity$Outbound` instead. */
  export type Outbound = GetConnectionByIdSecurity$Outbound;
}

export function getConnectionByIdSecurityToJSON(
  getConnectionByIdSecurity: GetConnectionByIdSecurity,
): string {
  return JSON.stringify(
    GetConnectionByIdSecurity$outboundSchema.parse(getConnectionByIdSecurity),
  );
}

export function getConnectionByIdSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectionByIdSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectionByIdSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectionByIdSecurity' from JSON`,
  );
}

/** @internal */
export const GetConnectionByIdRequest$inboundSchema: z.ZodType<
  GetConnectionByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
});

/** @internal */
export type GetConnectionByIdRequest$Outbound = {
  connectionId: string;
};

/** @internal */
export const GetConnectionByIdRequest$outboundSchema: z.ZodType<
  GetConnectionByIdRequest$Outbound,
  z.ZodTypeDef,
  GetConnectionByIdRequest
> = z.object({
  connectionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConnectionByIdRequest$ {
  /** @deprecated use `GetConnectionByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetConnectionByIdRequest$inboundSchema;
  /** @deprecated use `GetConnectionByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetConnectionByIdRequest$outboundSchema;
  /** @deprecated use `GetConnectionByIdRequest$Outbound` instead. */
  export type Outbound = GetConnectionByIdRequest$Outbound;
}

export function getConnectionByIdRequestToJSON(
  getConnectionByIdRequest: GetConnectionByIdRequest,
): string {
  return JSON.stringify(
    GetConnectionByIdRequest$outboundSchema.parse(getConnectionByIdRequest),
  );
}

export function getConnectionByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectionByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectionByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectionByIdRequest' from JSON`,
  );
}
