/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetConnectionPromptSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type GetConnectionPromptRequest = {
  /**
   * Unique identifier of the connection.
   */
  connectionId: string;
  /**
   * Name of the prompt template.
   */
  promptName: string;
  promptGetBody?: components.PromptGetBody | undefined;
};

/** @internal */
export const GetConnectionPromptSecurity$inboundSchema: z.ZodType<
  GetConnectionPromptSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type GetConnectionPromptSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const GetConnectionPromptSecurity$outboundSchema: z.ZodType<
  GetConnectionPromptSecurity$Outbound,
  z.ZodTypeDef,
  GetConnectionPromptSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConnectionPromptSecurity$ {
  /** @deprecated use `GetConnectionPromptSecurity$inboundSchema` instead. */
  export const inboundSchema = GetConnectionPromptSecurity$inboundSchema;
  /** @deprecated use `GetConnectionPromptSecurity$outboundSchema` instead. */
  export const outboundSchema = GetConnectionPromptSecurity$outboundSchema;
  /** @deprecated use `GetConnectionPromptSecurity$Outbound` instead. */
  export type Outbound = GetConnectionPromptSecurity$Outbound;
}

export function getConnectionPromptSecurityToJSON(
  getConnectionPromptSecurity: GetConnectionPromptSecurity,
): string {
  return JSON.stringify(
    GetConnectionPromptSecurity$outboundSchema.parse(
      getConnectionPromptSecurity,
    ),
  );
}

export function getConnectionPromptSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectionPromptSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectionPromptSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectionPromptSecurity' from JSON`,
  );
}

/** @internal */
export const GetConnectionPromptRequest$inboundSchema: z.ZodType<
  GetConnectionPromptRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
  promptName: z.string(),
  PromptGetBody: components.PromptGetBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "PromptGetBody": "promptGetBody",
  });
});

/** @internal */
export type GetConnectionPromptRequest$Outbound = {
  connectionId: string;
  promptName: string;
  PromptGetBody?: components.PromptGetBody$Outbound | undefined;
};

/** @internal */
export const GetConnectionPromptRequest$outboundSchema: z.ZodType<
  GetConnectionPromptRequest$Outbound,
  z.ZodTypeDef,
  GetConnectionPromptRequest
> = z.object({
  connectionId: z.string(),
  promptName: z.string(),
  promptGetBody: components.PromptGetBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    promptGetBody: "PromptGetBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConnectionPromptRequest$ {
  /** @deprecated use `GetConnectionPromptRequest$inboundSchema` instead. */
  export const inboundSchema = GetConnectionPromptRequest$inboundSchema;
  /** @deprecated use `GetConnectionPromptRequest$outboundSchema` instead. */
  export const outboundSchema = GetConnectionPromptRequest$outboundSchema;
  /** @deprecated use `GetConnectionPromptRequest$Outbound` instead. */
  export type Outbound = GetConnectionPromptRequest$Outbound;
}

export function getConnectionPromptRequestToJSON(
  getConnectionPromptRequest: GetConnectionPromptRequest,
): string {
  return JSON.stringify(
    GetConnectionPromptRequest$outboundSchema.parse(getConnectionPromptRequest),
  );
}

export function getConnectionPromptRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectionPromptRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectionPromptRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectionPromptRequest' from JSON`,
  );
}
