/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListConnectionPromptsSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type ListConnectionPromptsRequest = {
  /**
   * Unique identifier of the connection.
   */
  connectionId: string;
};

/** @internal */
export const ListConnectionPromptsSecurity$inboundSchema: z.ZodType<
  ListConnectionPromptsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListConnectionPromptsSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListConnectionPromptsSecurity$outboundSchema: z.ZodType<
  ListConnectionPromptsSecurity$Outbound,
  z.ZodTypeDef,
  ListConnectionPromptsSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListConnectionPromptsSecurity$ {
  /** @deprecated use `ListConnectionPromptsSecurity$inboundSchema` instead. */
  export const inboundSchema = ListConnectionPromptsSecurity$inboundSchema;
  /** @deprecated use `ListConnectionPromptsSecurity$outboundSchema` instead. */
  export const outboundSchema = ListConnectionPromptsSecurity$outboundSchema;
  /** @deprecated use `ListConnectionPromptsSecurity$Outbound` instead. */
  export type Outbound = ListConnectionPromptsSecurity$Outbound;
}

export function listConnectionPromptsSecurityToJSON(
  listConnectionPromptsSecurity: ListConnectionPromptsSecurity,
): string {
  return JSON.stringify(
    ListConnectionPromptsSecurity$outboundSchema.parse(
      listConnectionPromptsSecurity,
    ),
  );
}

export function listConnectionPromptsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListConnectionPromptsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConnectionPromptsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConnectionPromptsSecurity' from JSON`,
  );
}

/** @internal */
export const ListConnectionPromptsRequest$inboundSchema: z.ZodType<
  ListConnectionPromptsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
});

/** @internal */
export type ListConnectionPromptsRequest$Outbound = {
  connectionId: string;
};

/** @internal */
export const ListConnectionPromptsRequest$outboundSchema: z.ZodType<
  ListConnectionPromptsRequest$Outbound,
  z.ZodTypeDef,
  ListConnectionPromptsRequest
> = z.object({
  connectionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListConnectionPromptsRequest$ {
  /** @deprecated use `ListConnectionPromptsRequest$inboundSchema` instead. */
  export const inboundSchema = ListConnectionPromptsRequest$inboundSchema;
  /** @deprecated use `ListConnectionPromptsRequest$outboundSchema` instead. */
  export const outboundSchema = ListConnectionPromptsRequest$outboundSchema;
  /** @deprecated use `ListConnectionPromptsRequest$Outbound` instead. */
  export type Outbound = ListConnectionPromptsRequest$Outbound;
}

export function listConnectionPromptsRequestToJSON(
  listConnectionPromptsRequest: ListConnectionPromptsRequest,
): string {
  return JSON.stringify(
    ListConnectionPromptsRequest$outboundSchema.parse(
      listConnectionPromptsRequest,
    ),
  );
}

export function listConnectionPromptsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListConnectionPromptsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConnectionPromptsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConnectionPromptsRequest' from JSON`,
  );
}
