/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListModelsInContextSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type ListModelsInContextRequest = {
  /**
   * Unique identifier of the context
   */
  contextId: string;
};

/** @internal */
export const ListModelsInContextSecurity$inboundSchema: z.ZodType<
  ListModelsInContextSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListModelsInContextSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListModelsInContextSecurity$outboundSchema: z.ZodType<
  ListModelsInContextSecurity$Outbound,
  z.ZodTypeDef,
  ListModelsInContextSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListModelsInContextSecurity$ {
  /** @deprecated use `ListModelsInContextSecurity$inboundSchema` instead. */
  export const inboundSchema = ListModelsInContextSecurity$inboundSchema;
  /** @deprecated use `ListModelsInContextSecurity$outboundSchema` instead. */
  export const outboundSchema = ListModelsInContextSecurity$outboundSchema;
  /** @deprecated use `ListModelsInContextSecurity$Outbound` instead. */
  export type Outbound = ListModelsInContextSecurity$Outbound;
}

export function listModelsInContextSecurityToJSON(
  listModelsInContextSecurity: ListModelsInContextSecurity,
): string {
  return JSON.stringify(
    ListModelsInContextSecurity$outboundSchema.parse(
      listModelsInContextSecurity,
    ),
  );
}

export function listModelsInContextSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsInContextSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsInContextSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsInContextSecurity' from JSON`,
  );
}

/** @internal */
export const ListModelsInContextRequest$inboundSchema: z.ZodType<
  ListModelsInContextRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  contextId: z.string(),
});

/** @internal */
export type ListModelsInContextRequest$Outbound = {
  contextId: string;
};

/** @internal */
export const ListModelsInContextRequest$outboundSchema: z.ZodType<
  ListModelsInContextRequest$Outbound,
  z.ZodTypeDef,
  ListModelsInContextRequest
> = z.object({
  contextId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListModelsInContextRequest$ {
  /** @deprecated use `ListModelsInContextRequest$inboundSchema` instead. */
  export const inboundSchema = ListModelsInContextRequest$inboundSchema;
  /** @deprecated use `ListModelsInContextRequest$outboundSchema` instead. */
  export const outboundSchema = ListModelsInContextRequest$outboundSchema;
  /** @deprecated use `ListModelsInContextRequest$Outbound` instead. */
  export type Outbound = ListModelsInContextRequest$Outbound;
}

export function listModelsInContextRequestToJSON(
  listModelsInContextRequest: ListModelsInContextRequest,
): string {
  return JSON.stringify(
    ListModelsInContextRequest$outboundSchema.parse(listModelsInContextRequest),
  );
}

export function listModelsInContextRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsInContextRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsInContextRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsInContextRequest' from JSON`,
  );
}
