/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListConnectionResourcesSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type ListConnectionResourcesRequest = {
  /**
   * Unique identifier of the connection.
   */
  connectionId: string;
};

/** @internal */
export const ListConnectionResourcesSecurity$inboundSchema: z.ZodType<
  ListConnectionResourcesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListConnectionResourcesSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListConnectionResourcesSecurity$outboundSchema: z.ZodType<
  ListConnectionResourcesSecurity$Outbound,
  z.ZodTypeDef,
  ListConnectionResourcesSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListConnectionResourcesSecurity$ {
  /** @deprecated use `ListConnectionResourcesSecurity$inboundSchema` instead. */
  export const inboundSchema = ListConnectionResourcesSecurity$inboundSchema;
  /** @deprecated use `ListConnectionResourcesSecurity$outboundSchema` instead. */
  export const outboundSchema = ListConnectionResourcesSecurity$outboundSchema;
  /** @deprecated use `ListConnectionResourcesSecurity$Outbound` instead. */
  export type Outbound = ListConnectionResourcesSecurity$Outbound;
}

export function listConnectionResourcesSecurityToJSON(
  listConnectionResourcesSecurity: ListConnectionResourcesSecurity,
): string {
  return JSON.stringify(
    ListConnectionResourcesSecurity$outboundSchema.parse(
      listConnectionResourcesSecurity,
    ),
  );
}

export function listConnectionResourcesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListConnectionResourcesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConnectionResourcesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConnectionResourcesSecurity' from JSON`,
  );
}

/** @internal */
export const ListConnectionResourcesRequest$inboundSchema: z.ZodType<
  ListConnectionResourcesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
});

/** @internal */
export type ListConnectionResourcesRequest$Outbound = {
  connectionId: string;
};

/** @internal */
export const ListConnectionResourcesRequest$outboundSchema: z.ZodType<
  ListConnectionResourcesRequest$Outbound,
  z.ZodTypeDef,
  ListConnectionResourcesRequest
> = z.object({
  connectionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListConnectionResourcesRequest$ {
  /** @deprecated use `ListConnectionResourcesRequest$inboundSchema` instead. */
  export const inboundSchema = ListConnectionResourcesRequest$inboundSchema;
  /** @deprecated use `ListConnectionResourcesRequest$outboundSchema` instead. */
  export const outboundSchema = ListConnectionResourcesRequest$outboundSchema;
  /** @deprecated use `ListConnectionResourcesRequest$Outbound` instead. */
  export type Outbound = ListConnectionResourcesRequest$Outbound;
}

export function listConnectionResourcesRequestToJSON(
  listConnectionResourcesRequest: ListConnectionResourcesRequest,
): string {
  return JSON.stringify(
    ListConnectionResourcesRequest$outboundSchema.parse(
      listConnectionResourcesRequest,
    ),
  );
}

export function listConnectionResourcesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListConnectionResourcesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConnectionResourcesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConnectionResourcesRequest' from JSON`,
  );
}
