/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PingConnectionSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type PingConnectionRequest = {
  /**
   * Unique identifier of the connection
   */
  connectionId: string;
};

/** @internal */
export const PingConnectionSecurity$inboundSchema: z.ZodType<
  PingConnectionSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type PingConnectionSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const PingConnectionSecurity$outboundSchema: z.ZodType<
  PingConnectionSecurity$Outbound,
  z.ZodTypeDef,
  PingConnectionSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PingConnectionSecurity$ {
  /** @deprecated use `PingConnectionSecurity$inboundSchema` instead. */
  export const inboundSchema = PingConnectionSecurity$inboundSchema;
  /** @deprecated use `PingConnectionSecurity$outboundSchema` instead. */
  export const outboundSchema = PingConnectionSecurity$outboundSchema;
  /** @deprecated use `PingConnectionSecurity$Outbound` instead. */
  export type Outbound = PingConnectionSecurity$Outbound;
}

export function pingConnectionSecurityToJSON(
  pingConnectionSecurity: PingConnectionSecurity,
): string {
  return JSON.stringify(
    PingConnectionSecurity$outboundSchema.parse(pingConnectionSecurity),
  );
}

export function pingConnectionSecurityFromJSON(
  jsonString: string,
): SafeParseResult<PingConnectionSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PingConnectionSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PingConnectionSecurity' from JSON`,
  );
}

/** @internal */
export const PingConnectionRequest$inboundSchema: z.ZodType<
  PingConnectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionId: z.string(),
});

/** @internal */
export type PingConnectionRequest$Outbound = {
  connectionId: string;
};

/** @internal */
export const PingConnectionRequest$outboundSchema: z.ZodType<
  PingConnectionRequest$Outbound,
  z.ZodTypeDef,
  PingConnectionRequest
> = z.object({
  connectionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PingConnectionRequest$ {
  /** @deprecated use `PingConnectionRequest$inboundSchema` instead. */
  export const inboundSchema = PingConnectionRequest$inboundSchema;
  /** @deprecated use `PingConnectionRequest$outboundSchema` instead. */
  export const outboundSchema = PingConnectionRequest$outboundSchema;
  /** @deprecated use `PingConnectionRequest$Outbound` instead. */
  export type Outbound = PingConnectionRequest$Outbound;
}

export function pingConnectionRequestToJSON(
  pingConnectionRequest: PingConnectionRequest,
): string {
  return JSON.stringify(
    PingConnectionRequest$outboundSchema.parse(pingConnectionRequest),
  );
}

export function pingConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PingConnectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PingConnectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PingConnectionRequest' from JSON`,
  );
}
