/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostLogoutSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const PostLogoutSecurity$inboundSchema: z.ZodType<
  PostLogoutSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type PostLogoutSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const PostLogoutSecurity$outboundSchema: z.ZodType<
  PostLogoutSecurity$Outbound,
  z.ZodTypeDef,
  PostLogoutSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostLogoutSecurity$ {
  /** @deprecated use `PostLogoutSecurity$inboundSchema` instead. */
  export const inboundSchema = PostLogoutSecurity$inboundSchema;
  /** @deprecated use `PostLogoutSecurity$outboundSchema` instead. */
  export const outboundSchema = PostLogoutSecurity$outboundSchema;
  /** @deprecated use `PostLogoutSecurity$Outbound` instead. */
  export type Outbound = PostLogoutSecurity$Outbound;
}

export function postLogoutSecurityToJSON(
  postLogoutSecurity: PostLogoutSecurity,
): string {
  return JSON.stringify(
    PostLogoutSecurity$outboundSchema.parse(postLogoutSecurity),
  );
}

export function postLogoutSecurityFromJSON(
  jsonString: string,
): SafeParseResult<PostLogoutSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostLogoutSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLogoutSecurity' from JSON`,
  );
}
