/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribeResourceSecurity = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

export type SubscribeResourceRequest = {
  /**
   * Unique identifier of the resource
   */
  resourceId: string;
};

/** @internal */
export const SubscribeResourceSecurity$inboundSchema: z.ZodType<
  SubscribeResourceSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/** @internal */
export type SubscribeResourceSecurity$Outbound = {
  appSessionCookie?: string | undefined;
  bearerAuth?: string | undefined;
};

/** @internal */
export const SubscribeResourceSecurity$outboundSchema: z.ZodType<
  SubscribeResourceSecurity$Outbound,
  z.ZodTypeDef,
  SubscribeResourceSecurity
> = z.object({
  appSessionCookie: z.string().optional(),
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribeResourceSecurity$ {
  /** @deprecated use `SubscribeResourceSecurity$inboundSchema` instead. */
  export const inboundSchema = SubscribeResourceSecurity$inboundSchema;
  /** @deprecated use `SubscribeResourceSecurity$outboundSchema` instead. */
  export const outboundSchema = SubscribeResourceSecurity$outboundSchema;
  /** @deprecated use `SubscribeResourceSecurity$Outbound` instead. */
  export type Outbound = SubscribeResourceSecurity$Outbound;
}

export function subscribeResourceSecurityToJSON(
  subscribeResourceSecurity: SubscribeResourceSecurity,
): string {
  return JSON.stringify(
    SubscribeResourceSecurity$outboundSchema.parse(subscribeResourceSecurity),
  );
}

export function subscribeResourceSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeResourceSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeResourceSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeResourceSecurity' from JSON`,
  );
}

/** @internal */
export const SubscribeResourceRequest$inboundSchema: z.ZodType<
  SubscribeResourceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resourceId: z.string(),
});

/** @internal */
export type SubscribeResourceRequest$Outbound = {
  resourceId: string;
};

/** @internal */
export const SubscribeResourceRequest$outboundSchema: z.ZodType<
  SubscribeResourceRequest$Outbound,
  z.ZodTypeDef,
  SubscribeResourceRequest
> = z.object({
  resourceId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribeResourceRequest$ {
  /** @deprecated use `SubscribeResourceRequest$inboundSchema` instead. */
  export const inboundSchema = SubscribeResourceRequest$inboundSchema;
  /** @deprecated use `SubscribeResourceRequest$outboundSchema` instead. */
  export const outboundSchema = SubscribeResourceRequest$outboundSchema;
  /** @deprecated use `SubscribeResourceRequest$Outbound` instead. */
  export type Outbound = SubscribeResourceRequest$Outbound;
}

export function subscribeResourceRequestToJSON(
  subscribeResourceRequest: SubscribeResourceRequest,
): string {
  return JSON.stringify(
    SubscribeResourceRequest$outboundSchema.parse(subscribeResourceRequest),
  );
}

export function subscribeResourceRequestFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeResourceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeResourceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeResourceRequest' from JSON`,
  );
}
