/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.Utils;

public class AuthLoginBody {

    /**
     * Username or email
     */
    @JsonProperty("username")
    private String username;

    /**
     * User password
     */
    @JsonProperty("password")
    private String password;

    @JsonCreator
    public AuthLoginBody(
            @JsonProperty("username") String username,
            @JsonProperty("password") String password) {
        Utils.checkNotNull(username, "username");
        Utils.checkNotNull(password, "password");
        this.username = username;
        this.password = password;
    }

    /**
     * Username or email
     */
    @JsonIgnore
    public String username() {
        return username;
    }

    /**
     * User password
     */
    @JsonIgnore
    public String password() {
        return password;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Username or email
     */
    public AuthLoginBody withUsername(String username) {
        Utils.checkNotNull(username, "username");
        this.username = username;
        return this;
    }

    /**
     * User password
     */
    public AuthLoginBody withPassword(String password) {
        Utils.checkNotNull(password, "password");
        this.password = password;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthLoginBody other = (AuthLoginBody) o;
        return 
            Objects.deepEquals(this.username, other.username) &&
            Objects.deepEquals(this.password, other.password);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            username,
            password);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthLoginBody.class,
                "username", username,
                "password", password);
    }
    
    public final static class Builder {
 
        private String username;
 
        private String password;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Username or email
         */
        public Builder username(String username) {
            Utils.checkNotNull(username, "username");
            this.username = username;
            return this;
        }

        /**
         * User password
         */
        public Builder password(String password) {
            Utils.checkNotNull(password, "password");
            this.password = password;
            return this;
        }
        
        public AuthLoginBody build() {
            return new AuthLoginBody(
                username,
                password);
        }
    }
}
