/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * Capability
 * 
 * <p>Capability metadata for MCP servers
 */
public class Capability {

    /**
     * MCP server ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("serverId")
    private Optional<String> serverId;

    /**
     * List of supported capabilities
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("capabilities")
    private Optional<? extends List<String>> capabilities;

    @JsonCreator
    public Capability(
            @JsonProperty("serverId") Optional<String> serverId,
            @JsonProperty("capabilities") Optional<? extends List<String>> capabilities) {
        Utils.checkNotNull(serverId, "serverId");
        Utils.checkNotNull(capabilities, "capabilities");
        this.serverId = serverId;
        this.capabilities = capabilities;
    }
    
    public Capability() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * MCP server ID
     */
    @JsonIgnore
    public Optional<String> serverId() {
        return serverId;
    }

    /**
     * List of supported capabilities
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> capabilities() {
        return (Optional<List<String>>) capabilities;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * MCP server ID
     */
    public Capability withServerId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = Optional.ofNullable(serverId);
        return this;
    }

    /**
     * MCP server ID
     */
    public Capability withServerId(Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    /**
     * List of supported capabilities
     */
    public Capability withCapabilities(List<String> capabilities) {
        Utils.checkNotNull(capabilities, "capabilities");
        this.capabilities = Optional.ofNullable(capabilities);
        return this;
    }

    /**
     * List of supported capabilities
     */
    public Capability withCapabilities(Optional<? extends List<String>> capabilities) {
        Utils.checkNotNull(capabilities, "capabilities");
        this.capabilities = capabilities;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Capability other = (Capability) o;
        return 
            Objects.deepEquals(this.serverId, other.serverId) &&
            Objects.deepEquals(this.capabilities, other.capabilities);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            serverId,
            capabilities);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Capability.class,
                "serverId", serverId,
                "capabilities", capabilities);
    }
    
    public final static class Builder {
 
        private Optional<String> serverId = Optional.empty();
 
        private Optional<? extends List<String>> capabilities = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * MCP server ID
         */
        public Builder serverId(String serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = Optional.ofNullable(serverId);
            return this;
        }

        /**
         * MCP server ID
         */
        public Builder serverId(Optional<String> serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = serverId;
            return this;
        }

        /**
         * List of supported capabilities
         */
        public Builder capabilities(List<String> capabilities) {
            Utils.checkNotNull(capabilities, "capabilities");
            this.capabilities = Optional.ofNullable(capabilities);
            return this;
        }

        /**
         * List of supported capabilities
         */
        public Builder capabilities(Optional<? extends List<String>> capabilities) {
            Utils.checkNotNull(capabilities, "capabilities");
            this.capabilities = capabilities;
            return this;
        }
        
        public Capability build() {
            return new Capability(
                serverId,
                capabilities);
        }
    }
}
