/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ConnectionsBodyTransport
 * 
 * <p>Transport type (stdio or streamable-http)
 */
public enum ConnectionsBodyTransport {
    STDIO("stdio"),
    STREAMABLE_HTTP("streamable-http");

    @JsonValue
    private final String value;

    private ConnectionsBodyTransport(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ConnectionsBodyTransport> fromValue(String value) {
        for (ConnectionsBodyTransport o: ConnectionsBodyTransport.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

