/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class InlineResponse2005 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subscribed")
    private Optional<Boolean> subscribed;

    @JsonCreator
    public InlineResponse2005(
            @JsonProperty("subscribed") Optional<Boolean> subscribed) {
        Utils.checkNotNull(subscribed, "subscribed");
        this.subscribed = subscribed;
    }
    
    public InlineResponse2005() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<Boolean> subscribed() {
        return subscribed;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public InlineResponse2005 withSubscribed(boolean subscribed) {
        Utils.checkNotNull(subscribed, "subscribed");
        this.subscribed = Optional.ofNullable(subscribed);
        return this;
    }

    public InlineResponse2005 withSubscribed(Optional<Boolean> subscribed) {
        Utils.checkNotNull(subscribed, "subscribed");
        this.subscribed = subscribed;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2005 other = (InlineResponse2005) o;
        return 
            Objects.deepEquals(this.subscribed, other.subscribed);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            subscribed);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InlineResponse2005.class,
                "subscribed", subscribed);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> subscribed = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder subscribed(boolean subscribed) {
            Utils.checkNotNull(subscribed, "subscribed");
            this.subscribed = Optional.ofNullable(subscribed);
            return this;
        }

        public Builder subscribed(Optional<Boolean> subscribed) {
            Utils.checkNotNull(subscribed, "subscribed");
            this.subscribed = subscribed;
            return this;
        }
        
        public InlineResponse2005 build() {
            return new InlineResponse2005(
                subscribed);
        }
    }
}
