/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class InlineResponse202 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accepted")
    private Optional<Boolean> accepted;

    @JsonCreator
    public InlineResponse202(
            @JsonProperty("accepted") Optional<Boolean> accepted) {
        Utils.checkNotNull(accepted, "accepted");
        this.accepted = accepted;
    }
    
    public InlineResponse202() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<Boolean> accepted() {
        return accepted;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public InlineResponse202 withAccepted(boolean accepted) {
        Utils.checkNotNull(accepted, "accepted");
        this.accepted = Optional.ofNullable(accepted);
        return this;
    }

    public InlineResponse202 withAccepted(Optional<Boolean> accepted) {
        Utils.checkNotNull(accepted, "accepted");
        this.accepted = accepted;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse202 other = (InlineResponse202) o;
        return 
            Objects.deepEquals(this.accepted, other.accepted);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            accepted);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InlineResponse202.class,
                "accepted", accepted);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> accepted = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder accepted(boolean accepted) {
            Utils.checkNotNull(accepted, "accepted");
            this.accepted = Optional.ofNullable(accepted);
            return this;
        }

        public Builder accepted(Optional<Boolean> accepted) {
            Utils.checkNotNull(accepted, "accepted");
            this.accepted = accepted;
            return this;
        }
        
        public InlineResponse202 build() {
            return new InlineResponse202(
                accepted);
        }
    }
}
