/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * InlineResponse2003
 * 
 * <p>A user registered in the system
 */
public class InlineResponse2003 {

    /**
     * Primary key identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<Long> id;

    /**
     * Unique OpenID identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("openId")
    private Optional<String> openId;

    /**
     * User's name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * User's email address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private JsonNullable<String> email;

    /**
     * Method used for login
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("loginMethod")
    private JsonNullable<String> loginMethod;

    /**
     * User role in the system
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("role")
    private Optional<? extends InlineResponse2003Role> role;

    /**
     * Timestamp when user was created
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdAt")
    private Optional<OffsetDateTime> createdAt;

    /**
     * Timestamp when user was last updated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updatedAt")
    private Optional<OffsetDateTime> updatedAt;

    /**
     * Timestamp of last sign-in
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastSignedIn")
    private Optional<OffsetDateTime> lastSignedIn;

    @JsonCreator
    public InlineResponse2003(
            @JsonProperty("id") Optional<Long> id,
            @JsonProperty("openId") Optional<String> openId,
            @JsonProperty("name") JsonNullable<String> name,
            @JsonProperty("email") JsonNullable<String> email,
            @JsonProperty("loginMethod") JsonNullable<String> loginMethod,
            @JsonProperty("role") Optional<? extends InlineResponse2003Role> role,
            @JsonProperty("createdAt") Optional<OffsetDateTime> createdAt,
            @JsonProperty("updatedAt") Optional<OffsetDateTime> updatedAt,
            @JsonProperty("lastSignedIn") Optional<OffsetDateTime> lastSignedIn) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(openId, "openId");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(email, "email");
        Utils.checkNotNull(loginMethod, "loginMethod");
        Utils.checkNotNull(role, "role");
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(updatedAt, "updatedAt");
        Utils.checkNotNull(lastSignedIn, "lastSignedIn");
        this.id = id;
        this.openId = openId;
        this.name = name;
        this.email = email;
        this.loginMethod = loginMethod;
        this.role = role;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.lastSignedIn = lastSignedIn;
    }
    
    public InlineResponse2003() {
        this(Optional.empty(), Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Primary key identifier
     */
    @JsonIgnore
    public Optional<Long> id() {
        return id;
    }

    /**
     * Unique OpenID identifier
     */
    @JsonIgnore
    public Optional<String> openId() {
        return openId;
    }

    /**
     * User's name
     */
    @JsonIgnore
    public JsonNullable<String> name() {
        return name;
    }

    /**
     * User's email address
     */
    @JsonIgnore
    public JsonNullable<String> email() {
        return email;
    }

    /**
     * Method used for login
     */
    @JsonIgnore
    public JsonNullable<String> loginMethod() {
        return loginMethod;
    }

    /**
     * User role in the system
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<InlineResponse2003Role> role() {
        return (Optional<InlineResponse2003Role>) role;
    }

    /**
     * Timestamp when user was created
     */
    @JsonIgnore
    public Optional<OffsetDateTime> createdAt() {
        return createdAt;
    }

    /**
     * Timestamp when user was last updated
     */
    @JsonIgnore
    public Optional<OffsetDateTime> updatedAt() {
        return updatedAt;
    }

    /**
     * Timestamp of last sign-in
     */
    @JsonIgnore
    public Optional<OffsetDateTime> lastSignedIn() {
        return lastSignedIn;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Primary key identifier
     */
    public InlineResponse2003 withId(long id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * Primary key identifier
     */
    public InlineResponse2003 withId(Optional<Long> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Unique OpenID identifier
     */
    public InlineResponse2003 withOpenId(String openId) {
        Utils.checkNotNull(openId, "openId");
        this.openId = Optional.ofNullable(openId);
        return this;
    }

    /**
     * Unique OpenID identifier
     */
    public InlineResponse2003 withOpenId(Optional<String> openId) {
        Utils.checkNotNull(openId, "openId");
        this.openId = openId;
        return this;
    }

    /**
     * User's name
     */
    public InlineResponse2003 withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = JsonNullable.of(name);
        return this;
    }

    /**
     * User's name
     */
    public InlineResponse2003 withName(JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * User's email address
     */
    public InlineResponse2003 withEmail(String email) {
        Utils.checkNotNull(email, "email");
        this.email = JsonNullable.of(email);
        return this;
    }

    /**
     * User's email address
     */
    public InlineResponse2003 withEmail(JsonNullable<String> email) {
        Utils.checkNotNull(email, "email");
        this.email = email;
        return this;
    }

    /**
     * Method used for login
     */
    public InlineResponse2003 withLoginMethod(String loginMethod) {
        Utils.checkNotNull(loginMethod, "loginMethod");
        this.loginMethod = JsonNullable.of(loginMethod);
        return this;
    }

    /**
     * Method used for login
     */
    public InlineResponse2003 withLoginMethod(JsonNullable<String> loginMethod) {
        Utils.checkNotNull(loginMethod, "loginMethod");
        this.loginMethod = loginMethod;
        return this;
    }

    /**
     * User role in the system
     */
    public InlineResponse2003 withRole(InlineResponse2003Role role) {
        Utils.checkNotNull(role, "role");
        this.role = Optional.ofNullable(role);
        return this;
    }

    /**
     * User role in the system
     */
    public InlineResponse2003 withRole(Optional<? extends InlineResponse2003Role> role) {
        Utils.checkNotNull(role, "role");
        this.role = role;
        return this;
    }

    /**
     * Timestamp when user was created
     */
    public InlineResponse2003 withCreatedAt(OffsetDateTime createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = Optional.ofNullable(createdAt);
        return this;
    }

    /**
     * Timestamp when user was created
     */
    public InlineResponse2003 withCreatedAt(Optional<OffsetDateTime> createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Timestamp when user was last updated
     */
    public InlineResponse2003 withUpdatedAt(OffsetDateTime updatedAt) {
        Utils.checkNotNull(updatedAt, "updatedAt");
        this.updatedAt = Optional.ofNullable(updatedAt);
        return this;
    }

    /**
     * Timestamp when user was last updated
     */
    public InlineResponse2003 withUpdatedAt(Optional<OffsetDateTime> updatedAt) {
        Utils.checkNotNull(updatedAt, "updatedAt");
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Timestamp of last sign-in
     */
    public InlineResponse2003 withLastSignedIn(OffsetDateTime lastSignedIn) {
        Utils.checkNotNull(lastSignedIn, "lastSignedIn");
        this.lastSignedIn = Optional.ofNullable(lastSignedIn);
        return this;
    }

    /**
     * Timestamp of last sign-in
     */
    public InlineResponse2003 withLastSignedIn(Optional<OffsetDateTime> lastSignedIn) {
        Utils.checkNotNull(lastSignedIn, "lastSignedIn");
        this.lastSignedIn = lastSignedIn;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2003 other = (InlineResponse2003) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.openId, other.openId) &&
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.email, other.email) &&
            Objects.deepEquals(this.loginMethod, other.loginMethod) &&
            Objects.deepEquals(this.role, other.role) &&
            Objects.deepEquals(this.createdAt, other.createdAt) &&
            Objects.deepEquals(this.updatedAt, other.updatedAt) &&
            Objects.deepEquals(this.lastSignedIn, other.lastSignedIn);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            openId,
            name,
            email,
            loginMethod,
            role,
            createdAt,
            updatedAt,
            lastSignedIn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InlineResponse2003.class,
                "id", id,
                "openId", openId,
                "name", name,
                "email", email,
                "loginMethod", loginMethod,
                "role", role,
                "createdAt", createdAt,
                "updatedAt", updatedAt,
                "lastSignedIn", lastSignedIn);
    }
    
    public final static class Builder {
 
        private Optional<Long> id = Optional.empty();
 
        private Optional<String> openId = Optional.empty();
 
        private JsonNullable<String> name = JsonNullable.undefined();
 
        private JsonNullable<String> email = JsonNullable.undefined();
 
        private JsonNullable<String> loginMethod = JsonNullable.undefined();
 
        private Optional<? extends InlineResponse2003Role> role;
 
        private Optional<OffsetDateTime> createdAt = Optional.empty();
 
        private Optional<OffsetDateTime> updatedAt = Optional.empty();
 
        private Optional<OffsetDateTime> lastSignedIn = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Primary key identifier
         */
        public Builder id(long id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * Primary key identifier
         */
        public Builder id(Optional<Long> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * Unique OpenID identifier
         */
        public Builder openId(String openId) {
            Utils.checkNotNull(openId, "openId");
            this.openId = Optional.ofNullable(openId);
            return this;
        }

        /**
         * Unique OpenID identifier
         */
        public Builder openId(Optional<String> openId) {
            Utils.checkNotNull(openId, "openId");
            this.openId = openId;
            return this;
        }

        /**
         * User's name
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = JsonNullable.of(name);
            return this;
        }

        /**
         * User's name
         */
        public Builder name(JsonNullable<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * User's email address
         */
        public Builder email(String email) {
            Utils.checkNotNull(email, "email");
            this.email = JsonNullable.of(email);
            return this;
        }

        /**
         * User's email address
         */
        public Builder email(JsonNullable<String> email) {
            Utils.checkNotNull(email, "email");
            this.email = email;
            return this;
        }

        /**
         * Method used for login
         */
        public Builder loginMethod(String loginMethod) {
            Utils.checkNotNull(loginMethod, "loginMethod");
            this.loginMethod = JsonNullable.of(loginMethod);
            return this;
        }

        /**
         * Method used for login
         */
        public Builder loginMethod(JsonNullable<String> loginMethod) {
            Utils.checkNotNull(loginMethod, "loginMethod");
            this.loginMethod = loginMethod;
            return this;
        }

        /**
         * User role in the system
         */
        public Builder role(InlineResponse2003Role role) {
            Utils.checkNotNull(role, "role");
            this.role = Optional.ofNullable(role);
            return this;
        }

        /**
         * User role in the system
         */
        public Builder role(Optional<? extends InlineResponse2003Role> role) {
            Utils.checkNotNull(role, "role");
            this.role = role;
            return this;
        }

        /**
         * Timestamp when user was created
         */
        public Builder createdAt(OffsetDateTime createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * Timestamp when user was created
         */
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Timestamp when user was last updated
         */
        public Builder updatedAt(OffsetDateTime updatedAt) {
            Utils.checkNotNull(updatedAt, "updatedAt");
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * Timestamp when user was last updated
         */
        public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
            Utils.checkNotNull(updatedAt, "updatedAt");
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Timestamp of last sign-in
         */
        public Builder lastSignedIn(OffsetDateTime lastSignedIn) {
            Utils.checkNotNull(lastSignedIn, "lastSignedIn");
            this.lastSignedIn = Optional.ofNullable(lastSignedIn);
            return this;
        }

        /**
         * Timestamp of last sign-in
         */
        public Builder lastSignedIn(Optional<OffsetDateTime> lastSignedIn) {
            Utils.checkNotNull(lastSignedIn, "lastSignedIn");
            this.lastSignedIn = lastSignedIn;
            return this;
        }
        
        public InlineResponse2003 build() {
            if (role == null) {
                role = _SINGLETON_VALUE_Role.value();
            }
            return new InlineResponse2003(
                id,
                openId,
                name,
                email,
                loginMethod,
                role,
                createdAt,
                updatedAt,
                lastSignedIn);
        }

        private static final LazySingletonValue<Optional<? extends InlineResponse2003Role>> _SINGLETON_VALUE_Role =
                new LazySingletonValue<>(
                        "role",
                        "\"user\"",
                        new TypeReference<Optional<? extends InlineResponse2003Role>>() {});
    }
}
