/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class InlineResponse200 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ok")
    private Optional<Boolean> ok;

    @JsonCreator
    public InlineResponse200(
            @JsonProperty("ok") Optional<Boolean> ok) {
        Utils.checkNotNull(ok, "ok");
        this.ok = ok;
    }
    
    public InlineResponse200() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<Boolean> ok() {
        return ok;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public InlineResponse200 withOk(boolean ok) {
        Utils.checkNotNull(ok, "ok");
        this.ok = Optional.ofNullable(ok);
        return this;
    }

    public InlineResponse200 withOk(Optional<Boolean> ok) {
        Utils.checkNotNull(ok, "ok");
        this.ok = ok;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse200 other = (InlineResponse200) o;
        return 
            Objects.deepEquals(this.ok, other.ok);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            ok);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InlineResponse200.class,
                "ok", ok);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> ok = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder ok(boolean ok) {
            Utils.checkNotNull(ok, "ok");
            this.ok = Optional.ofNullable(ok);
            return this;
        }

        public Builder ok(Optional<Boolean> ok) {
            Utils.checkNotNull(ok, "ok");
            this.ok = ok;
            return this;
        }
        
        public InlineResponse200 build() {
            return new InlineResponse200(
                ok);
        }
    }
}
