/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class InlineResponse2006 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unsubscribed")
    private Optional<Boolean> unsubscribed;

    @JsonCreator
    public InlineResponse2006(
            @JsonProperty("unsubscribed") Optional<Boolean> unsubscribed) {
        Utils.checkNotNull(unsubscribed, "unsubscribed");
        this.unsubscribed = unsubscribed;
    }
    
    public InlineResponse2006() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<Boolean> unsubscribed() {
        return unsubscribed;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public InlineResponse2006 withUnsubscribed(boolean unsubscribed) {
        Utils.checkNotNull(unsubscribed, "unsubscribed");
        this.unsubscribed = Optional.ofNullable(unsubscribed);
        return this;
    }

    public InlineResponse2006 withUnsubscribed(Optional<Boolean> unsubscribed) {
        Utils.checkNotNull(unsubscribed, "unsubscribed");
        this.unsubscribed = unsubscribed;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2006 other = (InlineResponse2006) o;
        return 
            Objects.deepEquals(this.unsubscribed, other.unsubscribed);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            unsubscribed);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InlineResponse2006.class,
                "unsubscribed", unsubscribed);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> unsubscribed = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder unsubscribed(boolean unsubscribed) {
            Utils.checkNotNull(unsubscribed, "unsubscribed");
            this.unsubscribed = Optional.ofNullable(unsubscribed);
            return this;
        }

        public Builder unsubscribed(Optional<Boolean> unsubscribed) {
            Utils.checkNotNull(unsubscribed, "unsubscribed");
            this.unsubscribed = unsubscribed;
            return this;
        }
        
        public InlineResponse2006 build() {
            return new InlineResponse2006(
                unsubscribed);
        }
    }
}
