/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Level
 * 
 * <p>Logging level to set
 */
public enum Level {
    DEBUG("debug"),
    INFO("info"),
    WARN("warn"),
    ERROR("error"),
    FATAL("fatal");

    @JsonValue
    private final String value;

    private Level(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Level> fromValue(String value) {
        for (Level o: Level.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

