/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.Utils;

public class LoggingLevelBody {

    /**
     * Logging level to set
     */
    @JsonProperty("level")
    private Level level;

    @JsonCreator
    public LoggingLevelBody(
            @JsonProperty("level") Level level) {
        Utils.checkNotNull(level, "level");
        this.level = level;
    }

    /**
     * Logging level to set
     */
    @JsonIgnore
    public Level level() {
        return level;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Logging level to set
     */
    public LoggingLevelBody withLevel(Level level) {
        Utils.checkNotNull(level, "level");
        this.level = level;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LoggingLevelBody other = (LoggingLevelBody) o;
        return 
            Objects.deepEquals(this.level, other.level);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            level);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LoggingLevelBody.class,
                "level", level);
    }
    
    public final static class Builder {
 
        private Level level;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Logging level to set
         */
        public Builder level(Level level) {
            Utils.checkNotNull(level, "level");
            this.level = level;
            return this;
        }
        
        public LoggingLevelBody build() {
            return new LoggingLevelBody(
                level);
        }
    }
}
