/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Model
 * 
 * <p>Model within a context
 */
public class Model {

    /**
     * Unique model identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    /**
     * Associated context ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contextId")
    private Optional<String> contextId;

    /**
     * Model name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * Optional model description
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    /**
     * JSON schema or metadata describing the model structure
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schema")
    private Optional<? extends Map<String, Object>> schema;

    @JsonCreator
    public Model(
            @JsonProperty("id") Optional<String> id,
            @JsonProperty("contextId") Optional<String> contextId,
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("schema") Optional<? extends Map<String, Object>> schema) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(contextId, "contextId");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(schema, "schema");
        this.id = id;
        this.contextId = contextId;
        this.name = name;
        this.description = description;
        this.schema = schema;
    }
    
    public Model() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), JsonNullable.undefined(), Optional.empty());
    }

    /**
     * Unique model identifier
     */
    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    /**
     * Associated context ID
     */
    @JsonIgnore
    public Optional<String> contextId() {
        return contextId;
    }

    /**
     * Model name
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * Optional model description
     */
    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    /**
     * JSON schema or metadata describing the model structure
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> schema() {
        return (Optional<Map<String, Object>>) schema;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique model identifier
     */
    public Model withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * Unique model identifier
     */
    public Model withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Associated context ID
     */
    public Model withContextId(String contextId) {
        Utils.checkNotNull(contextId, "contextId");
        this.contextId = Optional.ofNullable(contextId);
        return this;
    }

    /**
     * Associated context ID
     */
    public Model withContextId(Optional<String> contextId) {
        Utils.checkNotNull(contextId, "contextId");
        this.contextId = contextId;
        return this;
    }

    /**
     * Model name
     */
    public Model withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    /**
     * Model name
     */
    public Model withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * Optional model description
     */
    public Model withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    /**
     * Optional model description
     */
    public Model withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * JSON schema or metadata describing the model structure
     */
    public Model withSchema(Map<String, Object> schema) {
        Utils.checkNotNull(schema, "schema");
        this.schema = Optional.ofNullable(schema);
        return this;
    }

    /**
     * JSON schema or metadata describing the model structure
     */
    public Model withSchema(Optional<? extends Map<String, Object>> schema) {
        Utils.checkNotNull(schema, "schema");
        this.schema = schema;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Model other = (Model) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.contextId, other.contextId) &&
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.description, other.description) &&
            Objects.deepEquals(this.schema, other.schema);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            contextId,
            name,
            description,
            schema);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Model.class,
                "id", id,
                "contextId", contextId,
                "name", name,
                "description", description,
                "schema", schema);
    }
    
    public final static class Builder {
 
        private Optional<String> id = Optional.empty();
 
        private Optional<String> contextId = Optional.empty();
 
        private Optional<String> name = Optional.empty();
 
        private JsonNullable<String> description = JsonNullable.undefined();
 
        private Optional<? extends Map<String, Object>> schema = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique model identifier
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * Unique model identifier
         */
        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * Associated context ID
         */
        public Builder contextId(String contextId) {
            Utils.checkNotNull(contextId, "contextId");
            this.contextId = Optional.ofNullable(contextId);
            return this;
        }

        /**
         * Associated context ID
         */
        public Builder contextId(Optional<String> contextId) {
            Utils.checkNotNull(contextId, "contextId");
            this.contextId = contextId;
            return this;
        }

        /**
         * Model name
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * Model name
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * Optional model description
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * Optional model description
         */
        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        /**
         * JSON schema or metadata describing the model structure
         */
        public Builder schema(Map<String, Object> schema) {
            Utils.checkNotNull(schema, "schema");
            this.schema = Optional.ofNullable(schema);
            return this;
        }

        /**
         * JSON schema or metadata describing the model structure
         */
        public Builder schema(Optional<? extends Map<String, Object>> schema) {
            Utils.checkNotNull(schema, "schema");
            this.schema = schema;
            return this;
        }
        
        public Model build() {
            return new Model(
                id,
                contextId,
                name,
                description,
                schema);
        }
    }
}
