/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class QueriesBody {

    /**
     * Target MCP server ID
     */
    @JsonProperty("serverId")
    private String serverId;

    /**
     * Target context ID
     */
    @JsonProperty("contextId")
    private String contextId;

    /**
     * Target model ID
     */
    @JsonProperty("modelId")
    private String modelId;

    /**
     * Query or command string to execute
     */
    @JsonProperty("query")
    private String query;

    /**
     * Optional parameters for the query
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parameters")
    private Optional<? extends Map<String, Object>> parameters;

    @JsonCreator
    public QueriesBody(
            @JsonProperty("serverId") String serverId,
            @JsonProperty("contextId") String contextId,
            @JsonProperty("modelId") String modelId,
            @JsonProperty("query") String query,
            @JsonProperty("parameters") Optional<? extends Map<String, Object>> parameters) {
        Utils.checkNotNull(serverId, "serverId");
        Utils.checkNotNull(contextId, "contextId");
        Utils.checkNotNull(modelId, "modelId");
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(parameters, "parameters");
        this.serverId = serverId;
        this.contextId = contextId;
        this.modelId = modelId;
        this.query = query;
        this.parameters = parameters;
    }
    
    public QueriesBody(
            String serverId,
            String contextId,
            String modelId,
            String query) {
        this(serverId, contextId, modelId, query, Optional.empty());
    }

    /**
     * Target MCP server ID
     */
    @JsonIgnore
    public String serverId() {
        return serverId;
    }

    /**
     * Target context ID
     */
    @JsonIgnore
    public String contextId() {
        return contextId;
    }

    /**
     * Target model ID
     */
    @JsonIgnore
    public String modelId() {
        return modelId;
    }

    /**
     * Query or command string to execute
     */
    @JsonIgnore
    public String query() {
        return query;
    }

    /**
     * Optional parameters for the query
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> parameters() {
        return (Optional<Map<String, Object>>) parameters;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Target MCP server ID
     */
    public QueriesBody withServerId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    /**
     * Target context ID
     */
    public QueriesBody withContextId(String contextId) {
        Utils.checkNotNull(contextId, "contextId");
        this.contextId = contextId;
        return this;
    }

    /**
     * Target model ID
     */
    public QueriesBody withModelId(String modelId) {
        Utils.checkNotNull(modelId, "modelId");
        this.modelId = modelId;
        return this;
    }

    /**
     * Query or command string to execute
     */
    public QueriesBody withQuery(String query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    /**
     * Optional parameters for the query
     */
    public QueriesBody withParameters(Map<String, Object> parameters) {
        Utils.checkNotNull(parameters, "parameters");
        this.parameters = Optional.ofNullable(parameters);
        return this;
    }

    /**
     * Optional parameters for the query
     */
    public QueriesBody withParameters(Optional<? extends Map<String, Object>> parameters) {
        Utils.checkNotNull(parameters, "parameters");
        this.parameters = parameters;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        QueriesBody other = (QueriesBody) o;
        return 
            Objects.deepEquals(this.serverId, other.serverId) &&
            Objects.deepEquals(this.contextId, other.contextId) &&
            Objects.deepEquals(this.modelId, other.modelId) &&
            Objects.deepEquals(this.query, other.query) &&
            Objects.deepEquals(this.parameters, other.parameters);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            serverId,
            contextId,
            modelId,
            query,
            parameters);
    }
    
    @Override
    public String toString() {
        return Utils.toString(QueriesBody.class,
                "serverId", serverId,
                "contextId", contextId,
                "modelId", modelId,
                "query", query,
                "parameters", parameters);
    }
    
    public final static class Builder {
 
        private String serverId;
 
        private String contextId;
 
        private String modelId;
 
        private String query;
 
        private Optional<? extends Map<String, Object>> parameters = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Target MCP server ID
         */
        public Builder serverId(String serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = serverId;
            return this;
        }

        /**
         * Target context ID
         */
        public Builder contextId(String contextId) {
            Utils.checkNotNull(contextId, "contextId");
            this.contextId = contextId;
            return this;
        }

        /**
         * Target model ID
         */
        public Builder modelId(String modelId) {
            Utils.checkNotNull(modelId, "modelId");
            this.modelId = modelId;
            return this;
        }

        /**
         * Query or command string to execute
         */
        public Builder query(String query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }

        /**
         * Optional parameters for the query
         */
        public Builder parameters(Map<String, Object> parameters) {
            Utils.checkNotNull(parameters, "parameters");
            this.parameters = Optional.ofNullable(parameters);
            return this;
        }

        /**
         * Optional parameters for the query
         */
        public Builder parameters(Optional<? extends Map<String, Object>> parameters) {
            Utils.checkNotNull(parameters, "parameters");
            this.parameters = parameters;
            return this;
        }
        
        public QueriesBody build() {
            return new QueriesBody(
                serverId,
                contextId,
                modelId,
                query,
                parameters);
        }
    }
}
