/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Resource
 * 
 * <p>MCP resource metadata
 */
public class Resource {

    /**
     * Unique resource identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    /**
     * MCP server ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("serverId")
    private Optional<String> serverId;

    /**
     * Resource name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * Optional resource description
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    @JsonCreator
    public Resource(
            @JsonProperty("id") Optional<String> id,
            @JsonProperty("serverId") Optional<String> serverId,
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("description") JsonNullable<String> description) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(serverId, "serverId");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(description, "description");
        this.id = id;
        this.serverId = serverId;
        this.name = name;
        this.description = description;
    }
    
    public Resource() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), JsonNullable.undefined());
    }

    /**
     * Unique resource identifier
     */
    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    /**
     * MCP server ID
     */
    @JsonIgnore
    public Optional<String> serverId() {
        return serverId;
    }

    /**
     * Resource name
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * Optional resource description
     */
    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique resource identifier
     */
    public Resource withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * Unique resource identifier
     */
    public Resource withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * MCP server ID
     */
    public Resource withServerId(String serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = Optional.ofNullable(serverId);
        return this;
    }

    /**
     * MCP server ID
     */
    public Resource withServerId(Optional<String> serverId) {
        Utils.checkNotNull(serverId, "serverId");
        this.serverId = serverId;
        return this;
    }

    /**
     * Resource name
     */
    public Resource withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    /**
     * Resource name
     */
    public Resource withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * Optional resource description
     */
    public Resource withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    /**
     * Optional resource description
     */
    public Resource withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Resource other = (Resource) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.serverId, other.serverId) &&
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.description, other.description);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            serverId,
            name,
            description);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Resource.class,
                "id", id,
                "serverId", serverId,
                "name", name,
                "description", description);
    }
    
    public final static class Builder {
 
        private Optional<String> id = Optional.empty();
 
        private Optional<String> serverId = Optional.empty();
 
        private Optional<String> name = Optional.empty();
 
        private JsonNullable<String> description = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique resource identifier
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * Unique resource identifier
         */
        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * MCP server ID
         */
        public Builder serverId(String serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = Optional.ofNullable(serverId);
            return this;
        }

        /**
         * MCP server ID
         */
        public Builder serverId(Optional<String> serverId) {
            Utils.checkNotNull(serverId, "serverId");
            this.serverId = serverId;
            return this;
        }

        /**
         * Resource name
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * Resource name
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * Optional resource description
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * Optional resource description
         */
        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }
        
        public Resource build() {
            return new Resource(
                id,
                serverId,
                name,
                description);
        }
    }
}
