/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.Utils;

public class SystemNotifyOwnerBody {

    /**
     * Notification title
     */
    @JsonProperty("title")
    private String title;

    /**
     * Notification content
     */
    @JsonProperty("content")
    private String content;

    @JsonCreator
    public SystemNotifyOwnerBody(
            @JsonProperty("title") String title,
            @JsonProperty("content") String content) {
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(content, "content");
        this.title = title;
        this.content = content;
    }

    /**
     * Notification title
     */
    @JsonIgnore
    public String title() {
        return title;
    }

    /**
     * Notification content
     */
    @JsonIgnore
    public String content() {
        return content;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Notification title
     */
    public SystemNotifyOwnerBody withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * Notification content
     */
    public SystemNotifyOwnerBody withContent(String content) {
        Utils.checkNotNull(content, "content");
        this.content = content;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SystemNotifyOwnerBody other = (SystemNotifyOwnerBody) o;
        return 
            Objects.deepEquals(this.title, other.title) &&
            Objects.deepEquals(this.content, other.content);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            title,
            content);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SystemNotifyOwnerBody.class,
                "title", title,
                "content", content);
    }
    
    public final static class Builder {
 
        private String title;
 
        private String content;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Notification title
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }

        /**
         * Notification content
         */
        public Builder content(String content) {
            Utils.checkNotNull(content, "content");
            this.content = content;
            return this;
        }
        
        public SystemNotifyOwnerBody build() {
            return new SystemNotifyOwnerBody(
                title,
                content);
        }
    }
}
