/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ToolCallResult {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isError")
    private Optional<Boolean> isError;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("content")
    private Optional<? extends List<Map<String, Object>>> content;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("structuredContent")
    private Optional<? extends Map<String, Object>> structuredContent;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends Map<String, Object>> metadata;

    @JsonCreator
    public ToolCallResult(
            @JsonProperty("isError") Optional<Boolean> isError,
            @JsonProperty("content") Optional<? extends List<Map<String, Object>>> content,
            @JsonProperty("structuredContent") Optional<? extends Map<String, Object>> structuredContent,
            @JsonProperty("metadata") Optional<? extends Map<String, Object>> metadata) {
        Utils.checkNotNull(isError, "isError");
        Utils.checkNotNull(content, "content");
        Utils.checkNotNull(structuredContent, "structuredContent");
        Utils.checkNotNull(metadata, "metadata");
        this.isError = isError;
        this.content = content;
        this.structuredContent = structuredContent;
        this.metadata = metadata;
    }
    
    public ToolCallResult() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<Boolean> isError() {
        return isError;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Map<String, Object>>> content() {
        return (Optional<List<Map<String, Object>>>) content;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> structuredContent() {
        return (Optional<Map<String, Object>>) structuredContent;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> metadata() {
        return (Optional<Map<String, Object>>) metadata;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public ToolCallResult withIsError(boolean isError) {
        Utils.checkNotNull(isError, "isError");
        this.isError = Optional.ofNullable(isError);
        return this;
    }

    public ToolCallResult withIsError(Optional<Boolean> isError) {
        Utils.checkNotNull(isError, "isError");
        this.isError = isError;
        return this;
    }

    public ToolCallResult withContent(List<Map<String, Object>> content) {
        Utils.checkNotNull(content, "content");
        this.content = Optional.ofNullable(content);
        return this;
    }

    public ToolCallResult withContent(Optional<? extends List<Map<String, Object>>> content) {
        Utils.checkNotNull(content, "content");
        this.content = content;
        return this;
    }

    public ToolCallResult withStructuredContent(Map<String, Object> structuredContent) {
        Utils.checkNotNull(structuredContent, "structuredContent");
        this.structuredContent = Optional.ofNullable(structuredContent);
        return this;
    }

    public ToolCallResult withStructuredContent(Optional<? extends Map<String, Object>> structuredContent) {
        Utils.checkNotNull(structuredContent, "structuredContent");
        this.structuredContent = structuredContent;
        return this;
    }

    public ToolCallResult withMetadata(Map<String, Object> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }

    public ToolCallResult withMetadata(Optional<? extends Map<String, Object>> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ToolCallResult other = (ToolCallResult) o;
        return 
            Objects.deepEquals(this.isError, other.isError) &&
            Objects.deepEquals(this.content, other.content) &&
            Objects.deepEquals(this.structuredContent, other.structuredContent) &&
            Objects.deepEquals(this.metadata, other.metadata);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            isError,
            content,
            structuredContent,
            metadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ToolCallResult.class,
                "isError", isError,
                "content", content,
                "structuredContent", structuredContent,
                "metadata", metadata);
    }
    
    public final static class Builder {
 
        private Optional<Boolean> isError = Optional.empty();
 
        private Optional<? extends List<Map<String, Object>>> content = Optional.empty();
 
        private Optional<? extends Map<String, Object>> structuredContent = Optional.empty();
 
        private Optional<? extends Map<String, Object>> metadata = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder isError(boolean isError) {
            Utils.checkNotNull(isError, "isError");
            this.isError = Optional.ofNullable(isError);
            return this;
        }

        public Builder isError(Optional<Boolean> isError) {
            Utils.checkNotNull(isError, "isError");
            this.isError = isError;
            return this;
        }

        public Builder content(List<Map<String, Object>> content) {
            Utils.checkNotNull(content, "content");
            this.content = Optional.ofNullable(content);
            return this;
        }

        public Builder content(Optional<? extends List<Map<String, Object>>> content) {
            Utils.checkNotNull(content, "content");
            this.content = content;
            return this;
        }

        public Builder structuredContent(Map<String, Object> structuredContent) {
            Utils.checkNotNull(structuredContent, "structuredContent");
            this.structuredContent = Optional.ofNullable(structuredContent);
            return this;
        }

        public Builder structuredContent(Optional<? extends Map<String, Object>> structuredContent) {
            Utils.checkNotNull(structuredContent, "structuredContent");
            this.structuredContent = structuredContent;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        public Builder metadata(Optional<? extends Map<String, Object>> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }
        
        public ToolCallResult build() {
            return new ToolCallResult(
                isError,
                content,
                structuredContent,
                metadata);
        }
    }
}
