/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * TransportOptionsStdio
 * 
 * <p>Transport options for stdio-based MCP servers.
 */
public class TransportOptionsStdio {

    /**
     * Executable used to launch the MCP server process.
     */
    @JsonProperty("command")
    private String command;

    /**
     * Optional command-line arguments.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("args")
    private Optional<? extends List<String>> args;

    /**
     * Environment variables passed to the child process.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("env")
    private Optional<? extends Map<String, String>> env;

    /**
     * Working directory for the child process.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cwd")
    private Optional<String> cwd;

    @JsonCreator
    public TransportOptionsStdio(
            @JsonProperty("command") String command,
            @JsonProperty("args") Optional<? extends List<String>> args,
            @JsonProperty("env") Optional<? extends Map<String, String>> env,
            @JsonProperty("cwd") Optional<String> cwd) {
        Utils.checkNotNull(command, "command");
        Utils.checkNotNull(args, "args");
        Utils.checkNotNull(env, "env");
        Utils.checkNotNull(cwd, "cwd");
        this.command = command;
        this.args = args;
        this.env = env;
        this.cwd = cwd;
    }
    
    public TransportOptionsStdio(
            String command) {
        this(command, Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Executable used to launch the MCP server process.
     */
    @JsonIgnore
    public String command() {
        return command;
    }

    /**
     * Optional command-line arguments.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> args() {
        return (Optional<List<String>>) args;
    }

    /**
     * Environment variables passed to the child process.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, String>> env() {
        return (Optional<Map<String, String>>) env;
    }

    /**
     * Working directory for the child process.
     */
    @JsonIgnore
    public Optional<String> cwd() {
        return cwd;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Executable used to launch the MCP server process.
     */
    public TransportOptionsStdio withCommand(String command) {
        Utils.checkNotNull(command, "command");
        this.command = command;
        return this;
    }

    /**
     * Optional command-line arguments.
     */
    public TransportOptionsStdio withArgs(List<String> args) {
        Utils.checkNotNull(args, "args");
        this.args = Optional.ofNullable(args);
        return this;
    }

    /**
     * Optional command-line arguments.
     */
    public TransportOptionsStdio withArgs(Optional<? extends List<String>> args) {
        Utils.checkNotNull(args, "args");
        this.args = args;
        return this;
    }

    /**
     * Environment variables passed to the child process.
     */
    public TransportOptionsStdio withEnv(Map<String, String> env) {
        Utils.checkNotNull(env, "env");
        this.env = Optional.ofNullable(env);
        return this;
    }

    /**
     * Environment variables passed to the child process.
     */
    public TransportOptionsStdio withEnv(Optional<? extends Map<String, String>> env) {
        Utils.checkNotNull(env, "env");
        this.env = env;
        return this;
    }

    /**
     * Working directory for the child process.
     */
    public TransportOptionsStdio withCwd(String cwd) {
        Utils.checkNotNull(cwd, "cwd");
        this.cwd = Optional.ofNullable(cwd);
        return this;
    }

    /**
     * Working directory for the child process.
     */
    public TransportOptionsStdio withCwd(Optional<String> cwd) {
        Utils.checkNotNull(cwd, "cwd");
        this.cwd = cwd;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransportOptionsStdio other = (TransportOptionsStdio) o;
        return 
            Objects.deepEquals(this.command, other.command) &&
            Objects.deepEquals(this.args, other.args) &&
            Objects.deepEquals(this.env, other.env) &&
            Objects.deepEquals(this.cwd, other.cwd);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            command,
            args,
            env,
            cwd);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TransportOptionsStdio.class,
                "command", command,
                "args", args,
                "env", env,
                "cwd", cwd);
    }
    
    public final static class Builder {
 
        private String command;
 
        private Optional<? extends List<String>> args = Optional.empty();
 
        private Optional<? extends Map<String, String>> env = Optional.empty();
 
        private Optional<String> cwd = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Executable used to launch the MCP server process.
         */
        public Builder command(String command) {
            Utils.checkNotNull(command, "command");
            this.command = command;
            return this;
        }

        /**
         * Optional command-line arguments.
         */
        public Builder args(List<String> args) {
            Utils.checkNotNull(args, "args");
            this.args = Optional.ofNullable(args);
            return this;
        }

        /**
         * Optional command-line arguments.
         */
        public Builder args(Optional<? extends List<String>> args) {
            Utils.checkNotNull(args, "args");
            this.args = args;
            return this;
        }

        /**
         * Environment variables passed to the child process.
         */
        public Builder env(Map<String, String> env) {
            Utils.checkNotNull(env, "env");
            this.env = Optional.ofNullable(env);
            return this;
        }

        /**
         * Environment variables passed to the child process.
         */
        public Builder env(Optional<? extends Map<String, String>> env) {
            Utils.checkNotNull(env, "env");
            this.env = env;
            return this;
        }

        /**
         * Working directory for the child process.
         */
        public Builder cwd(String cwd) {
            Utils.checkNotNull(cwd, "cwd");
            this.cwd = Optional.ofNullable(cwd);
            return this;
        }

        /**
         * Working directory for the child process.
         */
        public Builder cwd(Optional<String> cwd) {
            Utils.checkNotNull(cwd, "cwd");
            this.cwd = cwd;
            return this;
        }
        
        public TransportOptionsStdio build() {
            return new TransportOptionsStdio(
                command,
                args,
                env,
                cwd);
        }
    }
}
