/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthLoginBody = {
  /**
   * Username or email
   */
  username: string;
  /**
   * User password
   */
  password: string;
};

/** @internal */
export const AuthLoginBody$inboundSchema: z.ZodType<
  AuthLoginBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
  password: z.string(),
});

/** @internal */
export type AuthLoginBody$Outbound = {
  username: string;
  password: string;
};

/** @internal */
export const AuthLoginBody$outboundSchema: z.ZodType<
  AuthLoginBody$Outbound,
  z.ZodTypeDef,
  AuthLoginBody
> = z.object({
  username: z.string(),
  password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthLoginBody$ {
  /** @deprecated use `AuthLoginBody$inboundSchema` instead. */
  export const inboundSchema = AuthLoginBody$inboundSchema;
  /** @deprecated use `AuthLoginBody$outboundSchema` instead. */
  export const outboundSchema = AuthLoginBody$outboundSchema;
  /** @deprecated use `AuthLoginBody$Outbound` instead. */
  export type Outbound = AuthLoginBody$Outbound;
}

export function authLoginBodyToJSON(authLoginBody: AuthLoginBody): string {
  return JSON.stringify(AuthLoginBody$outboundSchema.parse(authLoginBody));
}

export function authLoginBodyFromJSON(
  jsonString: string,
): SafeParseResult<AuthLoginBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthLoginBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthLoginBody' from JSON`,
  );
}
