/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Capability metadata for MCP servers
 */
export type Capability = {
  /**
   * MCP server ID
   */
  serverId?: string | undefined;
  /**
   * List of supported capabilities
   */
  capabilities?: Array<string> | undefined;
};

/** @internal */
export const Capability$inboundSchema: z.ZodType<
  Capability,
  z.ZodTypeDef,
  unknown
> = z.object({
  serverId: z.string().optional(),
  capabilities: z.array(z.string()).optional(),
});

/** @internal */
export type Capability$Outbound = {
  serverId?: string | undefined;
  capabilities?: Array<string> | undefined;
};

/** @internal */
export const Capability$outboundSchema: z.ZodType<
  Capability$Outbound,
  z.ZodTypeDef,
  Capability
> = z.object({
  serverId: z.string().optional(),
  capabilities: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Capability$ {
  /** @deprecated use `Capability$inboundSchema` instead. */
  export const inboundSchema = Capability$inboundSchema;
  /** @deprecated use `Capability$outboundSchema` instead. */
  export const outboundSchema = Capability$outboundSchema;
  /** @deprecated use `Capability$Outbound` instead. */
  export type Outbound = Capability$Outbound;
}

export function capabilityToJSON(capability: Capability): string {
  return JSON.stringify(Capability$outboundSchema.parse(capability));
}

export function capabilityFromJSON(
  jsonString: string,
): SafeParseResult<Capability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Capability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Capability' from JSON`,
  );
}
