/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Transport type used
 */
export const Transport = {
  Stdio: "stdio",
  StreamableHttp: "streamable-http",
} as const;
/**
 * Transport type used
 */
export type Transport = ClosedEnum<typeof Transport>;

/**
 * Current connection status
 */
export const ConnectionStatus = {
  Initializing: "initializing",
  Connected: "connected",
  Disconnected: "disconnected",
  Error: "error",
} as const;
/**
 * Current connection status
 */
export type ConnectionStatus = ClosedEnum<typeof ConnectionStatus>;

/**
 * MCP connection metadata and status
 */
export type Connection = {
  /**
   * Unique connection identifier
   */
  id?: string | undefined;
  /**
   * MCP server ID connected to
   */
  serverId?: string | undefined;
  /**
   * Transport type used
   */
  transport?: Transport | undefined;
  /**
   * Current connection status
   */
  status?: ConnectionStatus | undefined;
  /**
   * Negotiated MCP protocol version
   */
  protocolVersion?: string | undefined;
  /**
   * List of server capabilities
   */
  capabilities?: Array<string> | undefined;
  /**
   * Timestamp when connection was created
   */
  createdAt?: Date | undefined;
  /**
   * Timestamp when connection was last updated
   */
  updatedAt?: Date | undefined;
};

/** @internal */
export const Transport$inboundSchema: z.ZodNativeEnum<typeof Transport> = z
  .nativeEnum(Transport);

/** @internal */
export const Transport$outboundSchema: z.ZodNativeEnum<typeof Transport> =
  Transport$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Transport$ {
  /** @deprecated use `Transport$inboundSchema` instead. */
  export const inboundSchema = Transport$inboundSchema;
  /** @deprecated use `Transport$outboundSchema` instead. */
  export const outboundSchema = Transport$outboundSchema;
}

/** @internal */
export const ConnectionStatus$inboundSchema: z.ZodNativeEnum<
  typeof ConnectionStatus
> = z.nativeEnum(ConnectionStatus);

/** @internal */
export const ConnectionStatus$outboundSchema: z.ZodNativeEnum<
  typeof ConnectionStatus
> = ConnectionStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectionStatus$ {
  /** @deprecated use `ConnectionStatus$inboundSchema` instead. */
  export const inboundSchema = ConnectionStatus$inboundSchema;
  /** @deprecated use `ConnectionStatus$outboundSchema` instead. */
  export const outboundSchema = ConnectionStatus$outboundSchema;
}

/** @internal */
export const Connection$inboundSchema: z.ZodType<
  Connection,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  serverId: z.string().optional(),
  transport: Transport$inboundSchema.optional(),
  status: ConnectionStatus$inboundSchema.optional(),
  protocolVersion: z.string().optional(),
  capabilities: z.array(z.string()).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

/** @internal */
export type Connection$Outbound = {
  id?: string | undefined;
  serverId?: string | undefined;
  transport?: string | undefined;
  status?: string | undefined;
  protocolVersion?: string | undefined;
  capabilities?: Array<string> | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

/** @internal */
export const Connection$outboundSchema: z.ZodType<
  Connection$Outbound,
  z.ZodTypeDef,
  Connection
> = z.object({
  id: z.string().optional(),
  serverId: z.string().optional(),
  transport: Transport$outboundSchema.optional(),
  status: ConnectionStatus$outboundSchema.optional(),
  protocolVersion: z.string().optional(),
  capabilities: z.array(z.string()).optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Connection$ {
  /** @deprecated use `Connection$inboundSchema` instead. */
  export const inboundSchema = Connection$inboundSchema;
  /** @deprecated use `Connection$outboundSchema` instead. */
  export const outboundSchema = Connection$outboundSchema;
  /** @deprecated use `Connection$Outbound` instead. */
  export type Outbound = Connection$Outbound;
}

export function connectionToJSON(connection: Connection): string {
  return JSON.stringify(Connection$outboundSchema.parse(connection));
}

export function connectionFromJSON(
  jsonString: string,
): SafeParseResult<Connection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connection' from JSON`,
  );
}
