/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TransportOptionsStdio,
  TransportOptionsStdio$inboundSchema,
  TransportOptionsStdio$Outbound,
  TransportOptionsStdio$outboundSchema,
} from "./transportoptionsstdio.js";
import {
  TransportOptionsStreamableHttp,
  TransportOptionsStreamableHttp$inboundSchema,
  TransportOptionsStreamableHttp$Outbound,
  TransportOptionsStreamableHttp$outboundSchema,
} from "./transportoptionsstreamablehttp.js";

/**
 * Transport type (stdio or streamable-http)
 */
export const ConnectionsBodyTransport = {
  Stdio: "stdio",
  StreamableHttp: "streamable-http",
} as const;
/**
 * Transport type (stdio or streamable-http)
 */
export type ConnectionsBodyTransport = ClosedEnum<
  typeof ConnectionsBodyTransport
>;

/**
 * Transport-specific options. Use stdio options for stdio connections and streamable HTTP options for streamable-http connections.
 */
export type Options = TransportOptionsStdio | TransportOptionsStreamableHttp;

export type ConnectionsBody = {
  /**
   * MCP server ID to connect to
   */
  serverId: string;
  /**
   * Transport type (stdio or streamable-http)
   */
  transport: ConnectionsBodyTransport;
  /**
   * Transport-specific options. Use stdio options for stdio connections and streamable HTTP options for streamable-http connections.
   */
  options?: TransportOptionsStdio | TransportOptionsStreamableHttp | undefined;
};

/** @internal */
export const ConnectionsBodyTransport$inboundSchema: z.ZodNativeEnum<
  typeof ConnectionsBodyTransport
> = z.nativeEnum(ConnectionsBodyTransport);

/** @internal */
export const ConnectionsBodyTransport$outboundSchema: z.ZodNativeEnum<
  typeof ConnectionsBodyTransport
> = ConnectionsBodyTransport$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectionsBodyTransport$ {
  /** @deprecated use `ConnectionsBodyTransport$inboundSchema` instead. */
  export const inboundSchema = ConnectionsBodyTransport$inboundSchema;
  /** @deprecated use `ConnectionsBodyTransport$outboundSchema` instead. */
  export const outboundSchema = ConnectionsBodyTransport$outboundSchema;
}

/** @internal */
export const Options$inboundSchema: z.ZodType<Options, z.ZodTypeDef, unknown> =
  z.union([
    TransportOptionsStdio$inboundSchema,
    TransportOptionsStreamableHttp$inboundSchema,
  ]);

/** @internal */
export type Options$Outbound =
  | TransportOptionsStdio$Outbound
  | TransportOptionsStreamableHttp$Outbound;

/** @internal */
export const Options$outboundSchema: z.ZodType<
  Options$Outbound,
  z.ZodTypeDef,
  Options
> = z.union([
  TransportOptionsStdio$outboundSchema,
  TransportOptionsStreamableHttp$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Options$ {
  /** @deprecated use `Options$inboundSchema` instead. */
  export const inboundSchema = Options$inboundSchema;
  /** @deprecated use `Options$outboundSchema` instead. */
  export const outboundSchema = Options$outboundSchema;
  /** @deprecated use `Options$Outbound` instead. */
  export type Outbound = Options$Outbound;
}

export function optionsToJSON(options: Options): string {
  return JSON.stringify(Options$outboundSchema.parse(options));
}

export function optionsFromJSON(
  jsonString: string,
): SafeParseResult<Options, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Options$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Options' from JSON`,
  );
}

/** @internal */
export const ConnectionsBody$inboundSchema: z.ZodType<
  ConnectionsBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  serverId: z.string(),
  transport: ConnectionsBodyTransport$inboundSchema,
  options: z.union([
    TransportOptionsStdio$inboundSchema,
    TransportOptionsStreamableHttp$inboundSchema,
  ]).optional(),
});

/** @internal */
export type ConnectionsBody$Outbound = {
  serverId: string;
  transport: string;
  options?:
    | TransportOptionsStdio$Outbound
    | TransportOptionsStreamableHttp$Outbound
    | undefined;
};

/** @internal */
export const ConnectionsBody$outboundSchema: z.ZodType<
  ConnectionsBody$Outbound,
  z.ZodTypeDef,
  ConnectionsBody
> = z.object({
  serverId: z.string(),
  transport: ConnectionsBodyTransport$outboundSchema,
  options: z.union([
    TransportOptionsStdio$outboundSchema,
    TransportOptionsStreamableHttp$outboundSchema,
  ]).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectionsBody$ {
  /** @deprecated use `ConnectionsBody$inboundSchema` instead. */
  export const inboundSchema = ConnectionsBody$inboundSchema;
  /** @deprecated use `ConnectionsBody$outboundSchema` instead. */
  export const outboundSchema = ConnectionsBody$outboundSchema;
  /** @deprecated use `ConnectionsBody$Outbound` instead. */
  export type Outbound = ConnectionsBody$Outbound;
}

export function connectionsBodyToJSON(
  connectionsBody: ConnectionsBody,
): string {
  return JSON.stringify(ConnectionsBody$outboundSchema.parse(connectionsBody));
}

export function connectionsBodyFromJSON(
  jsonString: string,
): SafeParseResult<ConnectionsBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectionsBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectionsBody' from JSON`,
  );
}
