/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InlineResponse2001 = {
  success?: boolean | undefined;
};

/** @internal */
export const InlineResponse2001$inboundSchema: z.ZodType<
  InlineResponse2001,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
});

/** @internal */
export type InlineResponse2001$Outbound = {
  success?: boolean | undefined;
};

/** @internal */
export const InlineResponse2001$outboundSchema: z.ZodType<
  InlineResponse2001$Outbound,
  z.ZodTypeDef,
  InlineResponse2001
> = z.object({
  success: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InlineResponse2001$ {
  /** @deprecated use `InlineResponse2001$inboundSchema` instead. */
  export const inboundSchema = InlineResponse2001$inboundSchema;
  /** @deprecated use `InlineResponse2001$outboundSchema` instead. */
  export const outboundSchema = InlineResponse2001$outboundSchema;
  /** @deprecated use `InlineResponse2001$Outbound` instead. */
  export type Outbound = InlineResponse2001$Outbound;
}

export function inlineResponse2001ToJSON(
  inlineResponse2001: InlineResponse2001,
): string {
  return JSON.stringify(
    InlineResponse2001$outboundSchema.parse(inlineResponse2001),
  );
}

export function inlineResponse2001FromJSON(
  jsonString: string,
): SafeParseResult<InlineResponse2001, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InlineResponse2001$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InlineResponse2001' from JSON`,
  );
}
