/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Current server status
 */
export const Status = {
  Online: "online",
  Offline: "offline",
} as const;
/**
 * Current server status
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * MCP server metadata
 */
export type McpServer = {
  /**
   * Unique server identifier
   */
  id?: string | undefined;
  /**
   * Server display name
   */
  name?: string | undefined;
  /**
   * Base URL of the MCP server
   */
  url?: string | undefined;
  /**
   * Optional server description
   */
  description?: string | null | undefined;
  /**
   * Current server status
   */
  status?: Status | undefined;
  /**
   * Server region or location
   */
  region?: string | null | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const McpServer$inboundSchema: z.ZodType<
  McpServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  url: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  status: Status$inboundSchema.optional(),
  region: z.nullable(z.string()).optional(),
});

/** @internal */
export type McpServer$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  url?: string | undefined;
  description?: string | null | undefined;
  status?: string | undefined;
  region?: string | null | undefined;
};

/** @internal */
export const McpServer$outboundSchema: z.ZodType<
  McpServer$Outbound,
  z.ZodTypeDef,
  McpServer
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  url: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  status: Status$outboundSchema.optional(),
  region: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpServer$ {
  /** @deprecated use `McpServer$inboundSchema` instead. */
  export const inboundSchema = McpServer$inboundSchema;
  /** @deprecated use `McpServer$outboundSchema` instead. */
  export const outboundSchema = McpServer$outboundSchema;
  /** @deprecated use `McpServer$Outbound` instead. */
  export type Outbound = McpServer$Outbound;
}

export function mcpServerToJSON(mcpServer: McpServer): string {
  return JSON.stringify(McpServer$outboundSchema.parse(mcpServer));
}

export function mcpServerFromJSON(
  jsonString: string,
): SafeParseResult<McpServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpServer' from JSON`,
  );
}
