/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RequestDetailsEvents = {
  timestamp?: Date | undefined;
  type?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const RequestDetailsEvents$inboundSchema: z.ZodType<
  RequestDetailsEvents,
  z.ZodTypeDef,
  unknown
> = z.object({
  timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  type: z.string().optional(),
  message: z.string().optional(),
});

/** @internal */
export type RequestDetailsEvents$Outbound = {
  timestamp?: string | undefined;
  type?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const RequestDetailsEvents$outboundSchema: z.ZodType<
  RequestDetailsEvents$Outbound,
  z.ZodTypeDef,
  RequestDetailsEvents
> = z.object({
  timestamp: z.date().transform(v => v.toISOString()).optional(),
  type: z.string().optional(),
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestDetailsEvents$ {
  /** @deprecated use `RequestDetailsEvents$inboundSchema` instead. */
  export const inboundSchema = RequestDetailsEvents$inboundSchema;
  /** @deprecated use `RequestDetailsEvents$outboundSchema` instead. */
  export const outboundSchema = RequestDetailsEvents$outboundSchema;
  /** @deprecated use `RequestDetailsEvents$Outbound` instead. */
  export type Outbound = RequestDetailsEvents$Outbound;
}

export function requestDetailsEventsToJSON(
  requestDetailsEvents: RequestDetailsEvents,
): string {
  return JSON.stringify(
    RequestDetailsEvents$outboundSchema.parse(requestDetailsEvents),
  );
}

export function requestDetailsEventsFromJSON(
  jsonString: string,
): SafeParseResult<RequestDetailsEvents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequestDetailsEvents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestDetailsEvents' from JSON`,
  );
}
