/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Template metadata for resources
 */
export type ResourceTemplate = {
  /**
   * Unique template identifier
   */
  id?: string | undefined;
  /**
   * Template name
   */
  name?: string | undefined;
  /**
   * Optional template description
   */
  description?: string | null | undefined;
};

/** @internal */
export const ResourceTemplate$inboundSchema: z.ZodType<
  ResourceTemplate,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

/** @internal */
export type ResourceTemplate$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const ResourceTemplate$outboundSchema: z.ZodType<
  ResourceTemplate$Outbound,
  z.ZodTypeDef,
  ResourceTemplate
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceTemplate$ {
  /** @deprecated use `ResourceTemplate$inboundSchema` instead. */
  export const inboundSchema = ResourceTemplate$inboundSchema;
  /** @deprecated use `ResourceTemplate$outboundSchema` instead. */
  export const outboundSchema = ResourceTemplate$outboundSchema;
  /** @deprecated use `ResourceTemplate$Outbound` instead. */
  export type Outbound = ResourceTemplate$Outbound;
}

export function resourceTemplateToJSON(
  resourceTemplate: ResourceTemplate,
): string {
  return JSON.stringify(
    ResourceTemplate$outboundSchema.parse(resourceTemplate),
  );
}

export function resourceTemplateFromJSON(
  jsonString: string,
): SafeParseResult<ResourceTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceTemplate' from JSON`,
  );
}
