/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Tool integrated within MCP Hub
 */
export type Tool = {
  /**
   * Unique tool identifier
   */
  id?: string | undefined;
  /**
   * Tool name
   */
  name?: string | undefined;
  /**
   * Tool description
   */
  description?: string | null | undefined;
  /**
   * Tool version
   */
  version?: string | undefined;
  /**
   * URL or endpoint to access the tool
   */
  url?: string | undefined;
};

/** @internal */
export const Tool$inboundSchema: z.ZodType<Tool, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    description: z.nullable(z.string()).optional(),
    version: z.string().optional(),
    url: z.string().optional(),
  });

/** @internal */
export type Tool$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  version?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const Tool$outboundSchema: z.ZodType<Tool$Outbound, z.ZodTypeDef, Tool> =
  z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    description: z.nullable(z.string()).optional(),
    version: z.string().optional(),
    url: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tool$ {
  /** @deprecated use `Tool$inboundSchema` instead. */
  export const inboundSchema = Tool$inboundSchema;
  /** @deprecated use `Tool$outboundSchema` instead. */
  export const outboundSchema = Tool$outboundSchema;
  /** @deprecated use `Tool$Outbound` instead. */
  export type Outbound = Tool$Outbound;
}

export function toolToJSON(tool: Tool): string {
  return JSON.stringify(Tool$outboundSchema.parse(tool));
}

export function toolFromJSON(
  jsonString: string,
): SafeParseResult<Tool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tool' from JSON`,
  );
}
