/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolCallBody = {
  /**
   * Arguments passed to the target tool.
   */
  arguments: { [k: string]: any };
  /**
   * Optional client-generated id for tracing.
   */
  requestId?: string | undefined;
};

/** @internal */
export const ToolCallBody$inboundSchema: z.ZodType<
  ToolCallBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  arguments: z.record(z.any()),
  requestId: z.string().optional(),
});

/** @internal */
export type ToolCallBody$Outbound = {
  arguments: { [k: string]: any };
  requestId?: string | undefined;
};

/** @internal */
export const ToolCallBody$outboundSchema: z.ZodType<
  ToolCallBody$Outbound,
  z.ZodTypeDef,
  ToolCallBody
> = z.object({
  arguments: z.record(z.any()),
  requestId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ToolCallBody$ {
  /** @deprecated use `ToolCallBody$inboundSchema` instead. */
  export const inboundSchema = ToolCallBody$inboundSchema;
  /** @deprecated use `ToolCallBody$outboundSchema` instead. */
  export const outboundSchema = ToolCallBody$outboundSchema;
  /** @deprecated use `ToolCallBody$Outbound` instead. */
  export type Outbound = ToolCallBody$Outbound;
}

export function toolCallBodyToJSON(toolCallBody: ToolCallBody): string {
  return JSON.stringify(ToolCallBody$outboundSchema.parse(toolCallBody));
}

export function toolCallBodyFromJSON(
  jsonString: string,
): SafeParseResult<ToolCallBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolCallBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolCallBody' from JSON`,
  );
}
