/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Transport options for streamable HTTP MCP servers.
 */
export type TransportOptionsStreamableHttp = {
  /**
   * HTTP endpoint for the MCP server transport.
   */
  url: string;
  /**
   * Optional HTTP headers sent with transport requests.
   */
  headers?: { [k: string]: string } | undefined;
  /**
   * Optional session identifier returned by the remote transport.
   */
  sessionId?: string | undefined;
};

/** @internal */
export const TransportOptionsStreamableHttp$inboundSchema: z.ZodType<
  TransportOptionsStreamableHttp,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  headers: z.record(z.string()).optional(),
  sessionId: z.string().optional(),
});

/** @internal */
export type TransportOptionsStreamableHttp$Outbound = {
  url: string;
  headers?: { [k: string]: string } | undefined;
  sessionId?: string | undefined;
};

/** @internal */
export const TransportOptionsStreamableHttp$outboundSchema: z.ZodType<
  TransportOptionsStreamableHttp$Outbound,
  z.ZodTypeDef,
  TransportOptionsStreamableHttp
> = z.object({
  url: z.string(),
  headers: z.record(z.string()).optional(),
  sessionId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransportOptionsStreamableHttp$ {
  /** @deprecated use `TransportOptionsStreamableHttp$inboundSchema` instead. */
  export const inboundSchema = TransportOptionsStreamableHttp$inboundSchema;
  /** @deprecated use `TransportOptionsStreamableHttp$outboundSchema` instead. */
  export const outboundSchema = TransportOptionsStreamableHttp$outboundSchema;
  /** @deprecated use `TransportOptionsStreamableHttp$Outbound` instead. */
  export type Outbound = TransportOptionsStreamableHttp$Outbound;
}

export function transportOptionsStreamableHttpToJSON(
  transportOptionsStreamableHttp: TransportOptionsStreamableHttp,
): string {
  return JSON.stringify(
    TransportOptionsStreamableHttp$outboundSchema.parse(
      transportOptionsStreamableHttp,
    ),
  );
}

export function transportOptionsStreamableHttpFromJSON(
  jsonString: string,
): SafeParseResult<TransportOptionsStreamableHttp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransportOptionsStreamableHttp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransportOptionsStreamableHttp' from JSON`,
  );
}
