/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Transport options for stdio-based MCP servers.
 */
export type TransportOptionsStdio = {
  /**
   * Executable used to launch the MCP server process.
   */
  command: string;
  /**
   * Optional command-line arguments.
   */
  args?: Array<string> | undefined;
  /**
   * Environment variables passed to the child process.
   */
  env?: { [k: string]: string } | undefined;
  /**
   * Working directory for the child process.
   */
  cwd?: string | undefined;
};

/** @internal */
export const TransportOptionsStdio$inboundSchema: z.ZodType<
  TransportOptionsStdio,
  z.ZodTypeDef,
  unknown
> = z.object({
  command: z.string(),
  args: z.array(z.string()).optional(),
  env: z.record(z.string()).optional(),
  cwd: z.string().optional(),
});

/** @internal */
export type TransportOptionsStdio$Outbound = {
  command: string;
  args?: Array<string> | undefined;
  env?: { [k: string]: string } | undefined;
  cwd?: string | undefined;
};

/** @internal */
export const TransportOptionsStdio$outboundSchema: z.ZodType<
  TransportOptionsStdio$Outbound,
  z.ZodTypeDef,
  TransportOptionsStdio
> = z.object({
  command: z.string(),
  args: z.array(z.string()).optional(),
  env: z.record(z.string()).optional(),
  cwd: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransportOptionsStdio$ {
  /** @deprecated use `TransportOptionsStdio$inboundSchema` instead. */
  export const inboundSchema = TransportOptionsStdio$inboundSchema;
  /** @deprecated use `TransportOptionsStdio$outboundSchema` instead. */
  export const outboundSchema = TransportOptionsStdio$outboundSchema;
  /** @deprecated use `TransportOptionsStdio$Outbound` instead. */
  export type Outbound = TransportOptionsStdio$Outbound;
}

export function transportOptionsStdioToJSON(
  transportOptionsStdio: TransportOptionsStdio,
): string {
  return JSON.stringify(
    TransportOptionsStdio$outboundSchema.parse(transportOptionsStdio),
  );
}

export function transportOptionsStdioFromJSON(
  jsonString: string,
): SafeParseResult<TransportOptionsStdio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransportOptionsStdio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransportOptionsStdio' from JSON`,
  );
}
